// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const aiModelDataSchema = z.object({
    ai_model_name: z.string().optional().nullable(),
    training_data: z.string().optional().nullable(),
    ai_model_size: z.string().optional().nullable(),
    inference_time_seconds: z.number().optional().nullable(),
    deployment_details: z.string().optional().nullable()
});
