// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const alertDataSchema = z.object({
    alert_details: z.string().optional().nullable(),
    alert_time: z.string().optional().nullable(),
    load_setpoint: z.number().optional().nullable(),
    generation_setpoint: z.number().optional().nullable(),
    predicted_security_state: z.string().optional().nullable(),
    confidence_bound: z.number().optional().nullable()
});
