// Generated by ts-to-zod
import { z } from "zod";

const metricsOutSchema = z.any();

const perAgentMetricsSchema = z.any();

export const collabMetricsResponseSchema = z.object({
    version: z.string().optional(),
    metrics_version: z.string().optional(),
    source: z.string(),
    params: z.record(z.string(), z.number().nullable()),
    metrics: metricsOutSchema,
    by_agent: z.array(perAgentMetricsSchema).optional()
});
