// Generated by ts-to-zod
import { z } from "zod";

const decisionSchema = z.any();

export const computeRequestSchema = z.object({
    decisions: z.array(decisionSchema),
    /**
     * Upper cap for reaction-time scaling (sec) used by HCL
     */
    rt_max: z.number().optional(),
    /**
     * Baseline duration for EL (efficiency/latency)
     */
    baseline_s: z.number().optional().nullable()
});
