// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const configRequestSchema = z.object({
    /**
     * Scenario name
     */
    task_name: z.string(),
    /**
     * Optional task description
     */
    task_description: z.string().optional().nullable(),
    task_parameters: z.record(z.string(), z.any()).optional(),
    agent_definitions: z.array(z.record(z.string(), z.any())).optional(),
    profile_definitions: z.array(z.record(z.string(), z.any())).optional(),
    /**
     * Optional file name or path (absolute under project root, repo-relative, or bare). Defaults to haic_env_builder/configs/<task>_env.yaml.
     */
    filename: z.string().optional().nullable()
});
