// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const decisionSchema = z.object({
    /**
     * Event timestamp (sec, monotonic within a session)
     */
    "t": z.number(),
    /**
     * Agent/human identifier
     */
    agent: z.string().optional().nullable(),
    /**
     * 'human' | 'ai' (used by HCL, per-agent stats)
     */
    actor_type: z.string().optional().nullable(),
    /**
     * Free-text action label
     */
    action: z.string().optional().nullable(),
    /**
     * Action duration (sec)
     */
    duration_s: z.number().optional().nullable(),
    /**
     * Alternative latency (ms) if duration_s missing
     */
    latency_ms: z.number().optional().nullable(),
    /**
     * Outcome for Tr/A (True/False)
     */
    correct: z.boolean().optional().nullable(),
    /**
     * Primary/human prob. distribution over classes
     */
    probs: z.record(z.string(), z.number()).optional().nullable(),
    /**
     * Surrogate model prob. distribution
     */
    surrogate_probs: z.record(z.string(), z.number()).optional().nullable(),
    /**
     * Fallback if no probs; compare with action
     */
    surrogate_action: z.string().optional().nullable(),
    /**
     * Optional: e.g., 'error' marks an error event
     */
    event_type: z.string().optional().nullable()
});
