// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const errorDetailSchema = z.object({
    code: z.string(),
    message: z.string(),
    details: z.record(z.string(), z.any()).optional()
});
