// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const ethicsResponsesSchema = z.object({
    /**
     * Fairness: The system handles different tasks (or users, data) without bias.
     */
    q_fairness: z.number(),
    /**
     * Transparency: I understand how the system/AI arrives at its suggestions or decisions.
     */
    q_transparency: z.number(),
    /**
     * Privacy: I feel confident that sensitive or personal data is protected by this system.
     */
    q_privacy: z.number(),
    /**
     * Accountability: It is clear who or what is responsible if the system makes a mistake.
     */
    q_accountability: z.number(),
    /**
     * Trust: Overall, I trust this system to operate ethically and in my best interest.
     */
    q_trust: z.number()
});
