// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const evaluationConfigSchemaSchema = z.object({
    id: z.number().optional().nullable(),
    application_name: z.string(),
    ai_model_name: z.string(),
    /**
     * One of: Classification, Regression, Clustering, XAI, Swarm Learning, Active Learning, Other
     */
    ai_model_type: z.string(),
    metrics: z.array(z.any()),
    evaluation_date: z.string().optional(),
    description: z.string().optional().nullable(),
    /**
     * Either 'specific' or 'generic'
     */
    config_type: z.string(),
    /**
     * Current status of the evaluation
     */
    evaluation_status: z.string().optional()
});
