// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const fairnessInputSchema = z.object({
    predictions: z.array(z.number()),
    labels: z.array(z.number()),
    sensitive_features: z.record(z.string(), z.array(z.string()))
});
