// Generated by ts-to-zod
import { z } from "zod";

const validationErrorSchema = z.any();

export const httpValidationErrorSchema = z.object({
    detail: z.array(validationErrorSchema).optional()
});
