// Generated by ts-to-zod
import { z } from "zod";

const validationDataSchema = z.any();

const reviewDataSchema = z.any();

const alertDataSchema = z.any();

export const interactionDataSchema = z.object({
    image_id: z.string().optional().nullable(),
    presentation_time: z.string().optional().nullable(),
    validation_data: validationDataSchema.optional().nullable(),
    review_data: reviewDataSchema.optional().nullable(),
    application_id: z.string().optional().nullable(),
    justification_documents: z.string().optional().nullable(),
    submission_time: z.string().optional().nullable(),
    load_generation_data: z.null().optional(),
    alert_data: z.union([alertDataSchema, z.array(alertDataSchema)]).optional().nullable()
});
