// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const likertScaleSchema = z.object({
    min: z.number().optional(),
    max: z.number().optional(),
    min_label: z.string().optional().nullable(),
    max_label: z.string().optional().nullable()
});
