// Generated by ts-to-zod
import { z } from "zod";

const interactionDataSchema = z.any();

const retrainEventSchema = z.any();

const performanceInfrastructureSchema = z.any();

const performanceLogsSchema = z.any();

const aiModelDataSchema = z.any();

export const logSchemaSchema = z.object({
    session_id: z.string(),
    user_id: z.string(),
    ai_model_version: z.string().optional().nullable(),
    app_version: z.string(),
    start_time: z.string(),
    end_time: z.string(),
    interaction_data: interactionDataSchema.optional().nullable(),
    retrain_events: z.array(retrainEventSchema).optional().nullable(),
    performance_infrastructure: performanceInfrastructureSchema.optional().nullable(),
    performance_logs: performanceLogsSchema.optional().nullable(),
    ai_model_data: aiModelDataSchema.optional().nullable(),
    decisions: z.null().optional()
});
