// Generated by ts-to-zod
import { z } from "zod";

const metricResponseSchema = z.any();

export const metricGroupResponseSchema = z.object({
    group_description: z.string().optional().nullable(),
    metrics: z.array(metricResponseSchema)
});
