// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const metricResponseSchema = z.object({
    name: z.string(),
    description: z.string().optional().nullable()
});
