// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const metricsOutSchema = z.object({
    "F": z.number(),
    "D": z.number(),
    HCL: z.number(),
    Tr: z.number(),
    "A": z.number(),
    "S": z.number(),
    EL: z.number()
});
