// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const performanceLogsSchema = z.object({
    processing_time_seconds: z.record(z.string(), z.number()).optional().nullable(),
    resource_utilization: z.record(z.string(), z.number()).optional().nullable(),
    human_effort_seconds: z.record(z.string(), z.number()).optional().nullable()
});
