// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const performanceInfrastructureSchema = z.object({
    hardware_specifications: z.string().optional().nullable(),
    software_stack: z.string().optional().nullable(),
    network_conditions: z.string().optional().nullable()
});
