// Generated by ts-to-zod
import { z } from "zod";

const likertScaleSchema = z.any();

export const questionSchema = z.object({
    /**
     * Stable identifier; also used as CSV column
     */
    id: z.string(),
    label: z.string(),
    type: z.string(),
    required: z.boolean().optional(),
    group: z.string().optional().nullable(),
    scale: likertScaleSchema.optional().nullable(),
    options: z.array(z.string()).optional().nullable()
});
