// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const retrainingDetailsSchema = z.object({
    time_taken_seconds: z.number().optional().nullable(),
    data_used: z.string().optional().nullable(),
    ai_model_version_after_retraining: z.string().optional().nullable()
});
