// Generated by ts-to-zod
import { z } from "zod";

const retrainingDetailsSchema = z.any();

export const retrainEventSchema = z.object({
    retraining_time: z.string().optional().nullable(),
    initial_metrics: z.record(z.string(), z.number()).optional().nullable(),
    post_retraining_metrics: z.record(z.string(), z.number()).optional().nullable(),
    retraining_details: retrainingDetailsSchema.optional().nullable()
});
