// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const reviewDataSchema = z.object({
    review_time_seconds: z.number().optional().nullable(),
    detections_confirmed: z.number().optional().nullable(),
    false_positives_identified: z.number().optional().nullable(),
    false_negatives_identified: z.number().optional().nullable(),
    feedback_details: z.string().optional().nullable(),
    time_spent_on_corrections_seconds: z.number().optional().nullable(),
    discrepancy_rate: z.number().optional().nullable(),
    operator_decision: z.string().optional().nullable(),
    feedback_time: z.string().optional().nullable(),
    insecure_instances_confirmed: z.number().optional().nullable(),
    false_positives: z.number().optional().nullable(),
    false_negatives: z.number().optional().nullable(),
    user_satisfaction: z.string().optional().nullable(),
    feedback_provided: z.string().optional().nullable(),
    human_confirmation_rate: z.number().optional().nullable()
});
