// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const simulationResultSchema = z.object({
    task: z.string(),
    agents: z.array(z.string()),
    profiles: z.array(z.string()),
    metrics: z.record(z.string(), z.number()),
    decisions: z.array(z.record(z.string(), z.any())),
    status: z.string(),
    seed: z.number().optional().nullable(),
    config_hash: z.string().optional().nullable(),
    log_path: z.string().optional().nullable()
});
