// Generated by ts-to-zod
import { z } from "zod";

const tamsusResponsesSchema = z.any();

const ethicsResponsesSchema = z.any();

export const surveyCreateSchema = z.object({
    /**
     * ID of the domain-specific question set used to render this survey
     */
    schema_id: z.string().optional().nullable(),
    survey_id: z.string().optional(),
    /**
     * An anonymized identifier for the respondent
     */
    user_id: z.string(),
    timestamp: z.string().optional(),
    /**
     * A tag indicating from which pilot this survey is received (e.g., 'SmartTicketing', 'SmartEnergy', etc.)
     */
    pilot_tag: z.string(),
    /**
     * Version of the pilot's application
     */
    app_version: z.string().optional().nullable(),
    /**
     * Version of the AI model being used
     */
    ai_model_version: z.string().optional().nullable(),
    tam_sus_responses: tamsusResponsesSchema,
    ethics_responses: ethicsResponsesSchema,
    /**
     * Optional domain-specific responses, e.g., for pilot-specific questions
     */
    domain_specific: z.record(z.string(), z.any()).optional().nullable()
});
