// Generated by ts-to-zod
import { z } from "zod";

const questionSchema = z.any();

export const surveyQuestionSetInSchema = z.object({
    name: z.string().optional().nullable(),
    pilot_tag: z.string().optional().nullable(),
    version: z.number().optional().nullable(),
    questions: z.array(questionSchema),
    active: z.boolean().optional(),
    created_by: z.string().optional().nullable()
});
