// Generated by ts-to-zod
import { z } from "zod";

/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const systemMetricsSchema = z.object({
    accuracy: z.number().optional().nullable(),
    precision: z.number().optional().nullable(),
    recall: z.number().optional().nullable()
});
