// Generated by ts-to-zod
import { z } from "zod";

const systemMetricsSchema = z.any();

export const validationDataSchema = z.object({
    ai_detection_results: z.string().optional().nullable(),
    confidence_scores: z.record(z.string(), z.number()).optional().nullable(),
    validation_results: z.string().optional().nullable(),
    confidence_level: z.number().optional().nullable(),
    processing_time_seconds: z.number().optional().nullable(),
    validation_time: z.string().optional().nullable(),
    system_metrics: systemMetricsSchema.optional().nullable()
});
