/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { googlerpcStatus } from './googlerpcStatus';
import type { v2beta1Url } from './v2beta1Url';
export type v2beta1PipelineVersion = {
    /**
     * Required input field. Unique ID of the parent pipeline.
     */
    pipeline_id?: string;
    /**
     * Output. Unique pipeline version ID. Generated by API server.
     */
    pipeline_version_id?: string;
    /**
     * Required input field. Pipeline version name provided by user.
     */
    display_name?: string;
    /**
     * Optional input field. Short description of the pipeline version.
     */
    description?: string;
    /**
     * Output. Creation time of the pipeline version.
     */
    created_at?: string;
    package_url?: v2beta1Url;
    /**
     * Input. Optional. The URL to the code source of the pipeline version.
     * The code is usually the Python definition of the pipeline and potentially
     * related the component definitions. This allows users to trace back to how
     * the pipeline YAML was created.
     */
    code_source_url?: string;
    /**
     * Output. The pipeline spec for the pipeline version.
     */
    pipeline_spec?: any;
    error?: googlerpcStatus;
};

