/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { googlerpcStatus } from './googlerpcStatus';
export type v2beta1Pipeline = {
    /**
     * Output. Unique pipeline ID. Generated by API server.
     */
    pipeline_id?: string;
    /**
     * Required input field. Pipeline name provided by user.
     */
    display_name?: string;
    /**
     * Optional input field. A short description of the pipeline.
     */
    description?: string;
    /**
     * Output. Creation time of the pipeline.
     */
    created_at?: string;
    /**
     * Input. A namespace this pipeline belongs to.
     * Causes error if user is not authorized to access the specified namespace.
     * If not specified in CreatePipeline, default namespace is used.
     */
    namespace?: string;
    error?: googlerpcStatus;
};

