/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { googlerpcStatus } from './googlerpcStatus';
import type { RecurringRunMode } from './RecurringRunMode';
import type { v2beta1PipelineVersionReference } from './v2beta1PipelineVersionReference';
import type { v2beta1RecurringRunStatus } from './v2beta1RecurringRunStatus';
import type { v2beta1RuntimeConfig } from './v2beta1RuntimeConfig';
import type { v2beta1Trigger } from './v2beta1Trigger';
export type v2beta1RecurringRun = {
    /**
     * Output. Unique run ID generated by API server.
     */
    recurring_run_id?: string;
    /**
     * Required input field. Recurring run name provided by user. Not unique.
     */
    display_name?: string;
    /**
     * Optional input field. Describes the purpose of the recurring run.
     */
    description?: string;
    /**
     * This field is Deprecated. The pipeline version id is under pipeline_version_reference for v2.
     */
    pipeline_version_id?: string;
    /**
     * The pipeline spec.
     */
    pipeline_spec?: any;
    pipeline_version_reference?: v2beta1PipelineVersionReference;
    runtime_config?: v2beta1RuntimeConfig;
    /**
     * Optional input field. Specifies which Kubernetes service account this recurring run uses.
     */
    service_account?: string;
    /**
     * Required input field.
     * Specifies how many runs can be executed concurrently. Range [1-10].
     */
    max_concurrency?: string;
    trigger?: v2beta1Trigger;
    mode?: RecurringRunMode;
    /**
     * Output. The time this recurring run was created.
     */
    created_at?: string;
    /**
     * Output. The last time this recurring run was updated.
     */
    updated_at?: string;
    status?: v2beta1RecurringRunStatus;
    error?: googlerpcStatus;
    /**
     * Optional input field. Whether the recurring run should catch up if behind schedule.
     * If true, the recurring run will only schedule the latest interval if behind schedule.
     * If false, the recurring run will catch up on each past interval.
     */
    no_catchup?: boolean;
    /**
     * TODO (gkclat): consider removing this field if it can be obtained from the parent experiment.
     * Output only. Namespace this recurring run belongs to. Derived from the parent experiment.
     */
    readonly namespace?: string;
    /**
     * ID of the parent experiment this recurring run belongs to.
     */
    experiment_id?: string;
};

