/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { v2beta1ExperimentStorageState } from './v2beta1ExperimentStorageState';
export type v2beta1Experiment = {
    /**
     * Output. Unique experiment ID. Generated by API server.
     */
    experiment_id?: string;
    /**
     * Required input field. Unique experiment name provided by user.
     */
    display_name?: string;
    /**
     * Optional input field. Describes the purpose of the experiment.
     */
    description?: string;
    /**
     * Output. The time that the experiment was created.
     */
    created_at?: string;
    /**
     * Optional input field. Specify the namespace this experiment belongs to.
     */
    namespace?: string;
    storage_state?: v2beta1ExperimentStorageState;
    /**
     * Output. The creation time of the last run in this experiment.
     */
    last_run_created_at?: string;
};

