/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { googlerpcStatus } from './googlerpcStatus';
import type { v2beta1PipelineVersionReference } from './v2beta1PipelineVersionReference';
import type { v2beta1RunDetails } from './v2beta1RunDetails';
import type { v2beta1RunStorageState } from './v2beta1RunStorageState';
import type { v2beta1RuntimeConfig } from './v2beta1RuntimeConfig';
import type { v2beta1RuntimeState } from './v2beta1RuntimeState';
import type { v2beta1RuntimeStatus } from './v2beta1RuntimeStatus';
export type v2beta1Run = {
    /**
     * Input. ID of the parent experiment.
     * The default experiment ID will be used if this is not specified.
     */
    experiment_id?: string;
    /**
     * Output. Unique run ID. Generated by API server.
     */
    run_id?: string;
    /**
     * Required input. Name provided by user,
     * or auto generated if run is created by a recurring run.
     */
    display_name?: string;
    storage_state?: v2beta1RunStorageState;
    /**
     * Optional input. Short description of the run.
     */
    description?: string;
    /**
     * This field is Deprecated. The pipeline version id is under pipeline_version_reference for v2.
     */
    pipeline_version_id?: string;
    /**
     * Pipeline spec.
     */
    pipeline_spec?: any;
    pipeline_version_reference?: v2beta1PipelineVersionReference;
    runtime_config?: v2beta1RuntimeConfig;
    /**
     * Optional input. Specifies which kubernetes service account is used.
     */
    service_account?: string;
    /**
     * Output. Creation time of the run.
     */
    created_at?: string;
    /**
     * Output. When this run is scheduled to start. This could be different from
     * created_at. For example, if a run is from a backfilling job that was supposed
     * to run 2 month ago, the created_at will be 2 month behind scheduled_at.
     */
    scheduled_at?: string;
    /**
     * Output. Completion of the run.
     */
    finished_at?: string;
    state?: v2beta1RuntimeState;
    error?: googlerpcStatus;
    run_details?: v2beta1RunDetails;
    /**
     * ID of the recurring run that triggered this run.
     */
    recurring_run_id?: string;
    /**
     * Output. A sequence of run statuses. This field keeps a record
     * of state transitions.
     */
    state_history?: Array<v2beta1RuntimeStatus>;
};

