/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { RuntimeError } from '../models';
import { V2beta1GetHealthzResponse } from '../models';
/**
 * HealthzServiceApi - axios parameter creator
 * @export
 */
export const HealthzServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get healthz data.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthzServiceGetHealthz: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/apis/v2beta1/healthz`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthzServiceApi - functional programming interface
 * @export
 */
export const HealthzServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get healthz data.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthzServiceGetHealthz(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1GetHealthzResponse>>> {
            const localVarAxiosArgs = await HealthzServiceApiAxiosParamCreator(configuration).healthzServiceGetHealthz(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * HealthzServiceApi - factory interface
 * @export
 */
export const HealthzServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get healthz data.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthzServiceGetHealthz(options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1GetHealthzResponse>> {
            return HealthzServiceApiFp(configuration).healthzServiceGetHealthz(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthzServiceApi - object-oriented interface
 * @export
 * @class HealthzServiceApi
 * @extends {BaseAPI}
 */
export class HealthzServiceApi extends BaseAPI {
    /**
     * 
     * @summary Get healthz data.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthzServiceApi
     */
    public async healthzServiceGetHealthz(options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1GetHealthzResponse>> {
        return HealthzServiceApiFp(this.configuration).healthzServiceGetHealthz(options).then((request) => request(this.axios, this.basePath));
    }
}
