/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GooglerpcStatus } from '../models';
import { V2beta1Pipeline } from '../models';
import { V2beta1PipelineVersion } from '../models';
/**
 * PipelineUploadServiceApi - axios parameter creator
 * @export
 */
export const PipelineUploadServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Blob} uploadfile 
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [namespace] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadPipelineForm: async (uploadfile: Blob, name?: string, description?: string, namespace?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uploadfile' is not null or undefined
            if (uploadfile === null || uploadfile === undefined) {
                throw new RequiredError('uploadfile','Required parameter uploadfile was null or undefined when calling uploadPipelineForm.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (description !== undefined) {
                localVarQueryParameter['description'] = description;
            }

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }


            if (uploadfile !== undefined) { 
                localVarFormParams.append('uploadfile', uploadfile as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Blob} uploadfile 
         * @param {string} [name] 
         * @param {string} [pipelineid] 
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadPipelineVersionForm: async (uploadfile: Blob, name?: string, pipelineid?: string, description?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uploadfile' is not null or undefined
            if (uploadfile === null || uploadfile === undefined) {
                throw new RequiredError('uploadfile','Required parameter uploadfile was null or undefined when calling uploadPipelineVersionForm.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/upload_version`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (pipelineid !== undefined) {
                localVarQueryParameter['pipelineid'] = pipelineid;
            }

            if (description !== undefined) {
                localVarQueryParameter['description'] = description;
            }


            if (uploadfile !== undefined) { 
                localVarFormParams.append('uploadfile', uploadfile as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PipelineUploadServiceApi - functional programming interface
 * @export
 */
export const PipelineUploadServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Blob} uploadfile 
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [namespace] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadPipelineForm(uploadfile: Blob, name?: string, description?: string, namespace?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1Pipeline>>> {
            const localVarAxiosArgs = await PipelineUploadServiceApiAxiosParamCreator(configuration).uploadPipelineForm(uploadfile, name, description, namespace, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {Blob} uploadfile 
         * @param {string} [name] 
         * @param {string} [pipelineid] 
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadPipelineVersionForm(uploadfile: Blob, name?: string, pipelineid?: string, description?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1PipelineVersion>>> {
            const localVarAxiosArgs = await PipelineUploadServiceApiAxiosParamCreator(configuration).uploadPipelineVersionForm(uploadfile, name, pipelineid, description, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PipelineUploadServiceApi - factory interface
 * @export
 */
export const PipelineUploadServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {Blob} uploadfile 
         * @param {string} [name] 
         * @param {string} [description] 
         * @param {string} [namespace] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadPipelineForm(uploadfile: Blob, name?: string, description?: string, namespace?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1Pipeline>> {
            return PipelineUploadServiceApiFp(configuration).uploadPipelineForm(uploadfile, name, description, namespace, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Blob} uploadfile 
         * @param {string} [name] 
         * @param {string} [pipelineid] 
         * @param {string} [description] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadPipelineVersionForm(uploadfile: Blob, name?: string, pipelineid?: string, description?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1PipelineVersion>> {
            return PipelineUploadServiceApiFp(configuration).uploadPipelineVersionForm(uploadfile, name, pipelineid, description, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PipelineUploadServiceApi - object-oriented interface
 * @export
 * @class PipelineUploadServiceApi
 * @extends {BaseAPI}
 */
export class PipelineUploadServiceApi extends BaseAPI {
    /**
     * 
     * @param {Blob} uploadfile 
     * @param {string} [name] 
     * @param {string} [description] 
     * @param {string} [namespace] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineUploadServiceApi
     */
    public async uploadPipelineForm(uploadfile: Blob, name?: string, description?: string, namespace?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1Pipeline>> {
        return PipelineUploadServiceApiFp(this.configuration).uploadPipelineForm(uploadfile, name, description, namespace, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {Blob} uploadfile 
     * @param {string} [name] 
     * @param {string} [pipelineid] 
     * @param {string} [description] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineUploadServiceApi
     */
    public async uploadPipelineVersionForm(uploadfile: Blob, name?: string, pipelineid?: string, description?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1PipelineVersion>> {
        return PipelineUploadServiceApiFp(this.configuration).uploadPipelineVersionForm(uploadfile, name, pipelineid, description, options).then((request) => request(this.axios, this.basePath));
    }
}
