/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { RuntimeError } from '../models';
import { V2beta1CreatePipelineAndVersionRequest } from '../models';
import { V2beta1ListPipelineVersionsResponse } from '../models';
import { V2beta1ListPipelinesResponse } from '../models';
import { V2beta1Pipeline } from '../models';
import { V2beta1PipelineVersion } from '../models';
/**
 * PipelineServiceApi - axios parameter creator
 * @export
 */
export const PipelineServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a pipeline.
         * @param {V2beta1Pipeline} body Required input. Pipeline that needs to be created.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceCreatePipeline: async (body: V2beta1Pipeline, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling pipelineServiceCreatePipeline.');
            }
            const localVarPath = `/apis/v2beta1/pipelines`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new pipeline and a new pipeline version in a single transaction.
         * @param {V2beta1CreatePipelineAndVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceCreatePipelineAndVersion: async (body: V2beta1CreatePipelineAndVersionRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling pipelineServiceCreatePipelineAndVersion.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Adds a pipeline version to the specified pipeline ID.
         * @param {V2beta1PipelineVersion} body Required input. Pipeline version ID to be created.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceCreatePipelineVersion: async (body: V2beta1PipelineVersion, pipelineId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling pipelineServiceCreatePipelineVersion.');
            }
            // verify required parameter 'pipelineId' is not null or undefined
            if (pipelineId === null || pipelineId === undefined) {
                throw new RequiredError('pipelineId','Required parameter pipelineId was null or undefined when calling pipelineServiceCreatePipelineVersion.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/{pipeline_id}/versions`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes an empty pipeline by ID. Returns error if the pipeline has pipeline versions.
         * @param {string} pipelineId Required input. ID of the pipeline to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceDeletePipeline: async (pipelineId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            if (pipelineId === null || pipelineId === undefined) {
                throw new RequiredError('pipelineId','Required parameter pipelineId was null or undefined when calling pipelineServiceDeletePipeline.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/{pipeline_id}`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a specific pipeline version by pipeline version ID and pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} pipelineVersionId Required input. The ID of the pipeline version to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceDeletePipelineVersion: async (pipelineId: string, pipelineVersionId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            if (pipelineId === null || pipelineId === undefined) {
                throw new RequiredError('pipelineId','Required parameter pipelineId was null or undefined when calling pipelineServiceDeletePipelineVersion.');
            }
            // verify required parameter 'pipelineVersionId' is not null or undefined
            if (pipelineVersionId === null || pipelineVersionId === undefined) {
                throw new RequiredError('pipelineVersionId','Required parameter pipelineVersionId was null or undefined when calling pipelineServiceDeletePipelineVersion.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/{pipeline_id}/versions/{pipeline_version_id}`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)))
                .replace(`{${"pipeline_version_id"}}`, encodeURIComponent(String(pipelineVersionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finds a specific pipeline by ID.
         * @param {string} pipelineId Required input. The ID of the pipeline to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceGetPipeline: async (pipelineId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            if (pipelineId === null || pipelineId === undefined) {
                throw new RequiredError('pipelineId','Required parameter pipelineId was null or undefined when calling pipelineServiceGetPipeline.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/{pipeline_id}`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finds a specific pipeline by name and namespace.
         * @param {string} name Required input. Name of the pipeline to be retrieved.
         * @param {string} [namespace] Optional input. Namespace of the pipeline.  It could be empty if default namespaces needs to be used or if multi-user  support is turned off.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceGetPipelineByName: async (name: string, namespace?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            if (name === null || name === undefined) {
                throw new RequiredError('name','Required parameter name was null or undefined when calling pipelineServiceGetPipelineByName.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/names/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a pipeline version by pipeline version ID and pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} pipelineVersionId Required input. ID of the pipeline version to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceGetPipelineVersion: async (pipelineId: string, pipelineVersionId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            if (pipelineId === null || pipelineId === undefined) {
                throw new RequiredError('pipelineId','Required parameter pipelineId was null or undefined when calling pipelineServiceGetPipelineVersion.');
            }
            // verify required parameter 'pipelineVersionId' is not null or undefined
            if (pipelineVersionId === null || pipelineVersionId === undefined) {
                throw new RequiredError('pipelineVersionId','Required parameter pipelineVersionId was null or undefined when calling pipelineServiceGetPipelineVersion.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/{pipeline_id}/versions/{pipeline_version_id}`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)))
                .replace(`{${"pipeline_version_id"}}`, encodeURIComponent(String(pipelineVersionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Lists all pipeline versions of a given pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} [pageToken] A page token to request the results page.
         * @param {number} [pageSize] The number of pipeline versions to be listed per page. If there are more pipeline versions than this number, the response message will contain a valid value in the nextPageToken field.
         * @param {string} [sortBy] Sorting order in form of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceListPipelineVersions: async (pipelineId: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            if (pipelineId === null || pipelineId === undefined) {
                throw new RequiredError('pipelineId','Required parameter pipelineId was null or undefined when calling pipelineServiceListPipelineVersions.');
            }
            const localVarPath = `/apis/v2beta1/pipelines/{pipeline_id}/versions`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (pageToken !== undefined) {
                localVarQueryParameter['page_token'] = pageToken;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finds all pipelines within a namespace.
         * @param {string} [namespace] Optional input. Namespace for the pipelines.
         * @param {string} [pageToken] A page token to request the results page.
         * @param {number} [pageSize] The number of pipelines to be listed per page. If there are more pipelines than this number, the response message will contain a valid value in the nextPageToken field.
         * @param {string} [sortBy] Sorting order in form of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pipelineServiceListPipelines: async (namespace?: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/apis/v2beta1/pipelines`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }

            if (pageToken !== undefined) {
                localVarQueryParameter['page_token'] = pageToken;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PipelineServiceApi - functional programming interface
 * @export
 */
export const PipelineServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a pipeline.
         * @param {V2beta1Pipeline} body Required input. Pipeline that needs to be created.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceCreatePipeline(body: V2beta1Pipeline, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1Pipeline>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceCreatePipeline(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Creates a new pipeline and a new pipeline version in a single transaction.
         * @param {V2beta1CreatePipelineAndVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceCreatePipelineAndVersion(body: V2beta1CreatePipelineAndVersionRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1Pipeline>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceCreatePipelineAndVersion(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Adds a pipeline version to the specified pipeline ID.
         * @param {V2beta1PipelineVersion} body Required input. Pipeline version ID to be created.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceCreatePipelineVersion(body: V2beta1PipelineVersion, pipelineId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1PipelineVersion>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceCreatePipelineVersion(body, pipelineId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes an empty pipeline by ID. Returns error if the pipeline has pipeline versions.
         * @param {string} pipelineId Required input. ID of the pipeline to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceDeletePipeline(pipelineId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceDeletePipeline(pipelineId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes a specific pipeline version by pipeline version ID and pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} pipelineVersionId Required input. The ID of the pipeline version to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceDeletePipelineVersion(pipelineId: string, pipelineVersionId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceDeletePipelineVersion(pipelineId, pipelineVersionId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Finds a specific pipeline by ID.
         * @param {string} pipelineId Required input. The ID of the pipeline to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceGetPipeline(pipelineId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1Pipeline>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceGetPipeline(pipelineId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Finds a specific pipeline by name and namespace.
         * @param {string} name Required input. Name of the pipeline to be retrieved.
         * @param {string} [namespace] Optional input. Namespace of the pipeline.  It could be empty if default namespaces needs to be used or if multi-user  support is turned off.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceGetPipelineByName(name: string, namespace?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1Pipeline>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceGetPipelineByName(name, namespace, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets a pipeline version by pipeline version ID and pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} pipelineVersionId Required input. ID of the pipeline version to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceGetPipelineVersion(pipelineId: string, pipelineVersionId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1PipelineVersion>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceGetPipelineVersion(pipelineId, pipelineVersionId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Lists all pipeline versions of a given pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} [pageToken] A page token to request the results page.
         * @param {number} [pageSize] The number of pipeline versions to be listed per page. If there are more pipeline versions than this number, the response message will contain a valid value in the nextPageToken field.
         * @param {string} [sortBy] Sorting order in form of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceListPipelineVersions(pipelineId: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1ListPipelineVersionsResponse>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceListPipelineVersions(pipelineId, pageToken, pageSize, sortBy, filter, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Finds all pipelines within a namespace.
         * @param {string} [namespace] Optional input. Namespace for the pipelines.
         * @param {string} [pageToken] A page token to request the results page.
         * @param {number} [pageSize] The number of pipelines to be listed per page. If there are more pipelines than this number, the response message will contain a valid value in the nextPageToken field.
         * @param {string} [sortBy] Sorting order in form of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceListPipelines(namespace?: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1ListPipelinesResponse>>> {
            const localVarAxiosArgs = await PipelineServiceApiAxiosParamCreator(configuration).pipelineServiceListPipelines(namespace, pageToken, pageSize, sortBy, filter, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PipelineServiceApi - factory interface
 * @export
 */
export const PipelineServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Creates a pipeline.
         * @param {V2beta1Pipeline} body Required input. Pipeline that needs to be created.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceCreatePipeline(body: V2beta1Pipeline, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1Pipeline>> {
            return PipelineServiceApiFp(configuration).pipelineServiceCreatePipeline(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new pipeline and a new pipeline version in a single transaction.
         * @param {V2beta1CreatePipelineAndVersionRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceCreatePipelineAndVersion(body: V2beta1CreatePipelineAndVersionRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1Pipeline>> {
            return PipelineServiceApiFp(configuration).pipelineServiceCreatePipelineAndVersion(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Adds a pipeline version to the specified pipeline ID.
         * @param {V2beta1PipelineVersion} body Required input. Pipeline version ID to be created.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceCreatePipelineVersion(body: V2beta1PipelineVersion, pipelineId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1PipelineVersion>> {
            return PipelineServiceApiFp(configuration).pipelineServiceCreatePipelineVersion(body, pipelineId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes an empty pipeline by ID. Returns error if the pipeline has pipeline versions.
         * @param {string} pipelineId Required input. ID of the pipeline to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceDeletePipeline(pipelineId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return PipelineServiceApiFp(configuration).pipelineServiceDeletePipeline(pipelineId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a specific pipeline version by pipeline version ID and pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} pipelineVersionId Required input. The ID of the pipeline version to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceDeletePipelineVersion(pipelineId: string, pipelineVersionId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return PipelineServiceApiFp(configuration).pipelineServiceDeletePipelineVersion(pipelineId, pipelineVersionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finds a specific pipeline by ID.
         * @param {string} pipelineId Required input. The ID of the pipeline to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceGetPipeline(pipelineId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1Pipeline>> {
            return PipelineServiceApiFp(configuration).pipelineServiceGetPipeline(pipelineId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finds a specific pipeline by name and namespace.
         * @param {string} name Required input. Name of the pipeline to be retrieved.
         * @param {string} [namespace] Optional input. Namespace of the pipeline.  It could be empty if default namespaces needs to be used or if multi-user  support is turned off.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceGetPipelineByName(name: string, namespace?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1Pipeline>> {
            return PipelineServiceApiFp(configuration).pipelineServiceGetPipelineByName(name, namespace, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a pipeline version by pipeline version ID and pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} pipelineVersionId Required input. ID of the pipeline version to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceGetPipelineVersion(pipelineId: string, pipelineVersionId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1PipelineVersion>> {
            return PipelineServiceApiFp(configuration).pipelineServiceGetPipelineVersion(pipelineId, pipelineVersionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Lists all pipeline versions of a given pipeline ID.
         * @param {string} pipelineId Required input. ID of the parent pipeline.
         * @param {string} [pageToken] A page token to request the results page.
         * @param {number} [pageSize] The number of pipeline versions to be listed per page. If there are more pipeline versions than this number, the response message will contain a valid value in the nextPageToken field.
         * @param {string} [sortBy] Sorting order in form of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceListPipelineVersions(pipelineId: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1ListPipelineVersionsResponse>> {
            return PipelineServiceApiFp(configuration).pipelineServiceListPipelineVersions(pipelineId, pageToken, pageSize, sortBy, filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finds all pipelines within a namespace.
         * @param {string} [namespace] Optional input. Namespace for the pipelines.
         * @param {string} [pageToken] A page token to request the results page.
         * @param {number} [pageSize] The number of pipelines to be listed per page. If there are more pipelines than this number, the response message will contain a valid value in the nextPageToken field.
         * @param {string} [sortBy] Sorting order in form of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pipelineServiceListPipelines(namespace?: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1ListPipelinesResponse>> {
            return PipelineServiceApiFp(configuration).pipelineServiceListPipelines(namespace, pageToken, pageSize, sortBy, filter, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PipelineServiceApi - object-oriented interface
 * @export
 * @class PipelineServiceApi
 * @extends {BaseAPI}
 */
export class PipelineServiceApi extends BaseAPI {
    /**
     * 
     * @summary Creates a pipeline.
     * @param {V2beta1Pipeline} body Required input. Pipeline that needs to be created.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceCreatePipeline(body: V2beta1Pipeline, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1Pipeline>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceCreatePipeline(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Creates a new pipeline and a new pipeline version in a single transaction.
     * @param {V2beta1CreatePipelineAndVersionRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceCreatePipelineAndVersion(body: V2beta1CreatePipelineAndVersionRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1Pipeline>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceCreatePipelineAndVersion(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Adds a pipeline version to the specified pipeline ID.
     * @param {V2beta1PipelineVersion} body Required input. Pipeline version ID to be created.
     * @param {string} pipelineId Required input. ID of the parent pipeline.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceCreatePipelineVersion(body: V2beta1PipelineVersion, pipelineId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1PipelineVersion>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceCreatePipelineVersion(body, pipelineId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes an empty pipeline by ID. Returns error if the pipeline has pipeline versions.
     * @param {string} pipelineId Required input. ID of the pipeline to be deleted.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceDeletePipeline(pipelineId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceDeletePipeline(pipelineId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes a specific pipeline version by pipeline version ID and pipeline ID.
     * @param {string} pipelineId Required input. ID of the parent pipeline.
     * @param {string} pipelineVersionId Required input. The ID of the pipeline version to be deleted.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceDeletePipelineVersion(pipelineId: string, pipelineVersionId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceDeletePipelineVersion(pipelineId, pipelineVersionId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Finds a specific pipeline by ID.
     * @param {string} pipelineId Required input. The ID of the pipeline to be retrieved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceGetPipeline(pipelineId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1Pipeline>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceGetPipeline(pipelineId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Finds a specific pipeline by name and namespace.
     * @param {string} name Required input. Name of the pipeline to be retrieved.
     * @param {string} [namespace] Optional input. Namespace of the pipeline.  It could be empty if default namespaces needs to be used or if multi-user  support is turned off.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceGetPipelineByName(name: string, namespace?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1Pipeline>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceGetPipelineByName(name, namespace, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets a pipeline version by pipeline version ID and pipeline ID.
     * @param {string} pipelineId Required input. ID of the parent pipeline.
     * @param {string} pipelineVersionId Required input. ID of the pipeline version to be retrieved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceGetPipelineVersion(pipelineId: string, pipelineVersionId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1PipelineVersion>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceGetPipelineVersion(pipelineId, pipelineVersionId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Lists all pipeline versions of a given pipeline ID.
     * @param {string} pipelineId Required input. ID of the parent pipeline.
     * @param {string} [pageToken] A page token to request the results page.
     * @param {number} [pageSize] The number of pipeline versions to be listed per page. If there are more pipeline versions than this number, the response message will contain a valid value in the nextPageToken field.
     * @param {string} [sortBy] Sorting order in form of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
     * @param {string} [filter] A url-encoded, JSON-serialized filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceListPipelineVersions(pipelineId: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1ListPipelineVersionsResponse>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceListPipelineVersions(pipelineId, pageToken, pageSize, sortBy, filter, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Finds all pipelines within a namespace.
     * @param {string} [namespace] Optional input. Namespace for the pipelines.
     * @param {string} [pageToken] A page token to request the results page.
     * @param {number} [pageSize] The number of pipelines to be listed per page. If there are more pipelines than this number, the response message will contain a valid value in the nextPageToken field.
     * @param {string} [sortBy] Sorting order in form of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
     * @param {string} [filter] A url-encoded, JSON-serialized filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelineServiceApi
     */
    public async pipelineServiceListPipelines(namespace?: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1ListPipelinesResponse>> {
        return PipelineServiceApiFp(this.configuration).pipelineServiceListPipelines(namespace, pageToken, pageSize, sortBy, filter, options).then((request) => request(this.axios, this.basePath));
    }
}
