/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { RuntimeError } from '../models';
import { V2beta1ListRecurringRunsResponse } from '../models';
import { V2beta1RecurringRun } from '../models';
/**
 * RecurringRunServiceApi - axios parameter creator
 * @export
 */
export const RecurringRunServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a new recurring run in an experiment, given the experiment ID.
         * @param {V2beta1RecurringRun} body The recurring run to be created.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recurringRunServiceCreateRecurringRun: async (body: V2beta1RecurringRun, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling recurringRunServiceCreateRecurringRun.');
            }
            const localVarPath = `/apis/v2beta1/recurringruns`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a recurring run.
         * @param {string} recurringRunId The ID of the recurring run to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recurringRunServiceDeleteRecurringRun: async (recurringRunId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recurringRunId' is not null or undefined
            if (recurringRunId === null || recurringRunId === undefined) {
                throw new RequiredError('recurringRunId','Required parameter recurringRunId was null or undefined when calling recurringRunServiceDeleteRecurringRun.');
            }
            const localVarPath = `/apis/v2beta1/recurringruns/{recurring_run_id}`
                .replace(`{${"recurring_run_id"}}`, encodeURIComponent(String(recurringRunId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Stops a recurring run and all its associated runs. The recurring run is not deleted.
         * @param {string} recurringRunId The ID of the recurring runs to be disabled.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recurringRunServiceDisableRecurringRun: async (recurringRunId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recurringRunId' is not null or undefined
            if (recurringRunId === null || recurringRunId === undefined) {
                throw new RequiredError('recurringRunId','Required parameter recurringRunId was null or undefined when calling recurringRunServiceDisableRecurringRun.');
            }
            const localVarPath = `/apis/v2beta1/recurringruns/{recurring_run_id}:disable`
                .replace(`{${"recurring_run_id"}}`, encodeURIComponent(String(recurringRunId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restarts a recurring run that was previously stopped. All runs associated with the  recurring run will continue.
         * @param {string} recurringRunId The ID of the recurring runs to be enabled.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recurringRunServiceEnableRecurringRun: async (recurringRunId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recurringRunId' is not null or undefined
            if (recurringRunId === null || recurringRunId === undefined) {
                throw new RequiredError('recurringRunId','Required parameter recurringRunId was null or undefined when calling recurringRunServiceEnableRecurringRun.');
            }
            const localVarPath = `/apis/v2beta1/recurringruns/{recurring_run_id}:enable`
                .replace(`{${"recurring_run_id"}}`, encodeURIComponent(String(recurringRunId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finds a specific recurring run by ID.
         * @param {string} recurringRunId The ID of the recurring run to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recurringRunServiceGetRecurringRun: async (recurringRunId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recurringRunId' is not null or undefined
            if (recurringRunId === null || recurringRunId === undefined) {
                throw new RequiredError('recurringRunId','Required parameter recurringRunId was null or undefined when calling recurringRunServiceGetRecurringRun.');
            }
            const localVarPath = `/apis/v2beta1/recurringruns/{recurring_run_id}`
                .replace(`{${"recurring_run_id"}}`, encodeURIComponent(String(recurringRunId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finds all recurring runs given experiment and namespace.  If experiment ID is not specified, find all recurring runs across all experiments.
         * @param {string} [pageToken] A page token to request the next page of results. The token is acquired from the nextPageToken field of the response from the previous ListRecurringRuns call or can be omitted when fetching the first page.
         * @param {number} [pageSize] The number of recurring runs to be listed per page. If there are more recurring runs  than this number, the response message will contain a nextPageToken field you can use to fetch the next page.
         * @param {string} [sortBy] Can be formatted as \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [namespace] Optional input. The namespace the recurring runs belong to.
         * @param {string} [filter] A url-encoded, JSON-serialized Filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {string} [experimentId] The ID of the experiment to be retrieved. If empty, list recurring runs across all experiments.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recurringRunServiceListRecurringRuns: async (pageToken?: string, pageSize?: number, sortBy?: string, namespace?: string, filter?: string, experimentId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/apis/v2beta1/recurringruns`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (pageToken !== undefined) {
                localVarQueryParameter['page_token'] = pageToken;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (experimentId !== undefined) {
                localVarQueryParameter['experiment_id'] = experimentId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecurringRunServiceApi - functional programming interface
 * @export
 */
export const RecurringRunServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Creates a new recurring run in an experiment, given the experiment ID.
         * @param {V2beta1RecurringRun} body The recurring run to be created.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceCreateRecurringRun(body: V2beta1RecurringRun, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1RecurringRun>>> {
            const localVarAxiosArgs = await RecurringRunServiceApiAxiosParamCreator(configuration).recurringRunServiceCreateRecurringRun(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes a recurring run.
         * @param {string} recurringRunId The ID of the recurring run to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceDeleteRecurringRun(recurringRunId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await RecurringRunServiceApiAxiosParamCreator(configuration).recurringRunServiceDeleteRecurringRun(recurringRunId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Stops a recurring run and all its associated runs. The recurring run is not deleted.
         * @param {string} recurringRunId The ID of the recurring runs to be disabled.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceDisableRecurringRun(recurringRunId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await RecurringRunServiceApiAxiosParamCreator(configuration).recurringRunServiceDisableRecurringRun(recurringRunId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Restarts a recurring run that was previously stopped. All runs associated with the  recurring run will continue.
         * @param {string} recurringRunId The ID of the recurring runs to be enabled.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceEnableRecurringRun(recurringRunId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await RecurringRunServiceApiAxiosParamCreator(configuration).recurringRunServiceEnableRecurringRun(recurringRunId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Finds a specific recurring run by ID.
         * @param {string} recurringRunId The ID of the recurring run to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceGetRecurringRun(recurringRunId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1RecurringRun>>> {
            const localVarAxiosArgs = await RecurringRunServiceApiAxiosParamCreator(configuration).recurringRunServiceGetRecurringRun(recurringRunId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Finds all recurring runs given experiment and namespace.  If experiment ID is not specified, find all recurring runs across all experiments.
         * @param {string} [pageToken] A page token to request the next page of results. The token is acquired from the nextPageToken field of the response from the previous ListRecurringRuns call or can be omitted when fetching the first page.
         * @param {number} [pageSize] The number of recurring runs to be listed per page. If there are more recurring runs  than this number, the response message will contain a nextPageToken field you can use to fetch the next page.
         * @param {string} [sortBy] Can be formatted as \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [namespace] Optional input. The namespace the recurring runs belong to.
         * @param {string} [filter] A url-encoded, JSON-serialized Filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {string} [experimentId] The ID of the experiment to be retrieved. If empty, list recurring runs across all experiments.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceListRecurringRuns(pageToken?: string, pageSize?: number, sortBy?: string, namespace?: string, filter?: string, experimentId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1ListRecurringRunsResponse>>> {
            const localVarAxiosArgs = await RecurringRunServiceApiAxiosParamCreator(configuration).recurringRunServiceListRecurringRuns(pageToken, pageSize, sortBy, namespace, filter, experimentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RecurringRunServiceApi - factory interface
 * @export
 */
export const RecurringRunServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Creates a new recurring run in an experiment, given the experiment ID.
         * @param {V2beta1RecurringRun} body The recurring run to be created.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceCreateRecurringRun(body: V2beta1RecurringRun, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1RecurringRun>> {
            return RecurringRunServiceApiFp(configuration).recurringRunServiceCreateRecurringRun(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a recurring run.
         * @param {string} recurringRunId The ID of the recurring run to be deleted.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceDeleteRecurringRun(recurringRunId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return RecurringRunServiceApiFp(configuration).recurringRunServiceDeleteRecurringRun(recurringRunId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Stops a recurring run and all its associated runs. The recurring run is not deleted.
         * @param {string} recurringRunId The ID of the recurring runs to be disabled.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceDisableRecurringRun(recurringRunId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return RecurringRunServiceApiFp(configuration).recurringRunServiceDisableRecurringRun(recurringRunId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restarts a recurring run that was previously stopped. All runs associated with the  recurring run will continue.
         * @param {string} recurringRunId The ID of the recurring runs to be enabled.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceEnableRecurringRun(recurringRunId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return RecurringRunServiceApiFp(configuration).recurringRunServiceEnableRecurringRun(recurringRunId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finds a specific recurring run by ID.
         * @param {string} recurringRunId The ID of the recurring run to be retrieved.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceGetRecurringRun(recurringRunId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1RecurringRun>> {
            return RecurringRunServiceApiFp(configuration).recurringRunServiceGetRecurringRun(recurringRunId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finds all recurring runs given experiment and namespace.  If experiment ID is not specified, find all recurring runs across all experiments.
         * @param {string} [pageToken] A page token to request the next page of results. The token is acquired from the nextPageToken field of the response from the previous ListRecurringRuns call or can be omitted when fetching the first page.
         * @param {number} [pageSize] The number of recurring runs to be listed per page. If there are more recurring runs  than this number, the response message will contain a nextPageToken field you can use to fetch the next page.
         * @param {string} [sortBy] Can be formatted as \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
         * @param {string} [namespace] Optional input. The namespace the recurring runs belong to.
         * @param {string} [filter] A url-encoded, JSON-serialized Filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {string} [experimentId] The ID of the experiment to be retrieved. If empty, list recurring runs across all experiments.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recurringRunServiceListRecurringRuns(pageToken?: string, pageSize?: number, sortBy?: string, namespace?: string, filter?: string, experimentId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1ListRecurringRunsResponse>> {
            return RecurringRunServiceApiFp(configuration).recurringRunServiceListRecurringRuns(pageToken, pageSize, sortBy, namespace, filter, experimentId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecurringRunServiceApi - object-oriented interface
 * @export
 * @class RecurringRunServiceApi
 * @extends {BaseAPI}
 */
export class RecurringRunServiceApi extends BaseAPI {
    /**
     * 
     * @summary Creates a new recurring run in an experiment, given the experiment ID.
     * @param {V2beta1RecurringRun} body The recurring run to be created.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringRunServiceApi
     */
    public async recurringRunServiceCreateRecurringRun(body: V2beta1RecurringRun, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1RecurringRun>> {
        return RecurringRunServiceApiFp(this.configuration).recurringRunServiceCreateRecurringRun(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes a recurring run.
     * @param {string} recurringRunId The ID of the recurring run to be deleted.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringRunServiceApi
     */
    public async recurringRunServiceDeleteRecurringRun(recurringRunId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return RecurringRunServiceApiFp(this.configuration).recurringRunServiceDeleteRecurringRun(recurringRunId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Stops a recurring run and all its associated runs. The recurring run is not deleted.
     * @param {string} recurringRunId The ID of the recurring runs to be disabled.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringRunServiceApi
     */
    public async recurringRunServiceDisableRecurringRun(recurringRunId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return RecurringRunServiceApiFp(this.configuration).recurringRunServiceDisableRecurringRun(recurringRunId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Restarts a recurring run that was previously stopped. All runs associated with the  recurring run will continue.
     * @param {string} recurringRunId The ID of the recurring runs to be enabled.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringRunServiceApi
     */
    public async recurringRunServiceEnableRecurringRun(recurringRunId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return RecurringRunServiceApiFp(this.configuration).recurringRunServiceEnableRecurringRun(recurringRunId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Finds a specific recurring run by ID.
     * @param {string} recurringRunId The ID of the recurring run to be retrieved.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringRunServiceApi
     */
    public async recurringRunServiceGetRecurringRun(recurringRunId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1RecurringRun>> {
        return RecurringRunServiceApiFp(this.configuration).recurringRunServiceGetRecurringRun(recurringRunId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Finds all recurring runs given experiment and namespace.  If experiment ID is not specified, find all recurring runs across all experiments.
     * @param {string} [pageToken] A page token to request the next page of results. The token is acquired from the nextPageToken field of the response from the previous ListRecurringRuns call or can be omitted when fetching the first page.
     * @param {number} [pageSize] The number of recurring runs to be listed per page. If there are more recurring runs  than this number, the response message will contain a nextPageToken field you can use to fetch the next page.
     * @param {string} [sortBy] Can be formatted as \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot;. Ascending by default.
     * @param {string} [namespace] Optional input. The namespace the recurring runs belong to.
     * @param {string} [filter] A url-encoded, JSON-serialized Filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
     * @param {string} [experimentId] The ID of the experiment to be retrieved. If empty, list recurring runs across all experiments.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecurringRunServiceApi
     */
    public async recurringRunServiceListRecurringRuns(pageToken?: string, pageSize?: number, sortBy?: string, namespace?: string, filter?: string, experimentId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1ListRecurringRunsResponse>> {
        return RecurringRunServiceApiFp(this.configuration).recurringRunServiceListRecurringRuns(pageToken, pageSize, sortBy, namespace, filter, experimentId, options).then((request) => request(this.axios, this.basePath));
    }
}
