/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { RuntimeError } from '../models';
import { V2beta1ListRunsResponse } from '../models';
import { V2beta1ReadArtifactResponse } from '../models';
import { V2beta1Run } from '../models';
/**
 * RunServiceApi - axios parameter creator
 * @export
 */
export const RunServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Archives a run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be archived.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceArchiveRun: async (runId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            if (runId === null || runId === undefined) {
                throw new RequiredError('runId','Required parameter runId was null or undefined when calling runServiceArchiveRun.');
            }
            const localVarPath = `/apis/v2beta1/runs/{run_id}:archive`
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new run in an experiment specified by experiment ID.  If experiment ID is not specified, the run is created in the default experiment.
         * @param {V2beta1Run} body Run to be created.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceCreateRun: async (body: V2beta1Run, experimentId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling runServiceCreateRun.');
            }
            const localVarPath = `/apis/v2beta1/runs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (experimentId !== undefined) {
                localVarQueryParameter['experiment_id'] = experimentId;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be deleted.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceDeleteRun: async (runId: string, experimentId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            if (runId === null || runId === undefined) {
                throw new RequiredError('runId','Required parameter runId was null or undefined when calling runServiceDeleteRun.');
            }
            const localVarPath = `/apis/v2beta1/runs/{run_id}`
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (experimentId !== undefined) {
                localVarQueryParameter['experiment_id'] = experimentId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finds a specific run by ID.
         * @param {string} runId The ID of the run to be retrieved.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceGetRun: async (runId: string, experimentId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            if (runId === null || runId === undefined) {
                throw new RequiredError('runId','Required parameter runId was null or undefined when calling runServiceGetRun.');
            }
            const localVarPath = `/apis/v2beta1/runs/{run_id}`
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (experimentId !== undefined) {
                localVarQueryParameter['experiment_id'] = experimentId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finds all runs in an experiment given by experiment ID.  If experiment id is not specified, finds all runs across all experiments.
         * @param {string} [namespace] Optional input field. Filters based on the namespace.
         * @param {string} [experimentId] The ID of the parent experiment. If empty, response includes runs across all experiments.
         * @param {string} [pageToken] A page token to request the next page of results. The token is acquired from the nextPageToken field of the response from the previous ListRuns call or can be omitted when fetching the first page.
         * @param {number} [pageSize] The number of runs to be listed per page. If there are more runs than this number, the response message will contain a nextPageToken field you can use to fetch the next page.
         * @param {string} [sortBy] Can be format of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot; (Example, \&quot;name asc\&quot; or \&quot;id desc\&quot;). Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized Filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceListRuns: async (namespace?: string, experimentId?: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/apis/v2beta1/runs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (namespace !== undefined) {
                localVarQueryParameter['namespace'] = namespace;
            }

            if (experimentId !== undefined) {
                localVarQueryParameter['experiment_id'] = experimentId;
            }

            if (pageToken !== undefined) {
                localVarQueryParameter['page_token'] = pageToken;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sort_by'] = sortBy;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Finds artifact data in a run.
         * @param {string} runId ID of the run.
         * @param {string} nodeId ID of the running node.
         * @param {string} artifactName Name of the artifact.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceReadArtifact: async (runId: string, nodeId: string, artifactName: string, experimentId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            if (runId === null || runId === undefined) {
                throw new RequiredError('runId','Required parameter runId was null or undefined when calling runServiceReadArtifact.');
            }
            // verify required parameter 'nodeId' is not null or undefined
            if (nodeId === null || nodeId === undefined) {
                throw new RequiredError('nodeId','Required parameter nodeId was null or undefined when calling runServiceReadArtifact.');
            }
            // verify required parameter 'artifactName' is not null or undefined
            if (artifactName === null || artifactName === undefined) {
                throw new RequiredError('artifactName','Required parameter artifactName was null or undefined when calling runServiceReadArtifact.');
            }
            const localVarPath = `/apis/v2beta1/runs/{run_id}/nodes/{node_id}/artifacts/{artifact_name}:read`
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)))
                .replace(`{${"node_id"}}`, encodeURIComponent(String(nodeId)))
                .replace(`{${"artifact_name"}}`, encodeURIComponent(String(artifactName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            if (experimentId !== undefined) {
                localVarQueryParameter['experiment_id'] = experimentId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Re-initiates a failed or terminated run.
         * @param {string} runId The ID of the run to be retried.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceRetryRun: async (runId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            if (runId === null || runId === undefined) {
                throw new RequiredError('runId','Required parameter runId was null or undefined when calling runServiceRetryRun.');
            }
            const localVarPath = `/apis/v2beta1/runs/{run_id}:retry`
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Terminates an active run.
         * @param {string} runId The ID of the run to be terminated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceTerminateRun: async (runId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            if (runId === null || runId === undefined) {
                throw new RequiredError('runId','Required parameter runId was null or undefined when calling runServiceTerminateRun.');
            }
            const localVarPath = `/apis/v2beta1/runs/{run_id}:terminate`
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Restores an archived run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be restored.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runServiceUnarchiveRun: async (runId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'runId' is not null or undefined
            if (runId === null || runId === undefined) {
                throw new RequiredError('runId','Required parameter runId was null or undefined when calling runServiceUnarchiveRun.');
            }
            const localVarPath = `/apis/v2beta1/runs/{run_id}:unarchive`
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RunServiceApi - functional programming interface
 * @export
 */
export const RunServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Archives a run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be archived.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceArchiveRun(runId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceArchiveRun(runId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Creates a new run in an experiment specified by experiment ID.  If experiment ID is not specified, the run is created in the default experiment.
         * @param {V2beta1Run} body Run to be created.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceCreateRun(body: V2beta1Run, experimentId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1Run>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceCreateRun(body, experimentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Deletes a run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be deleted.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceDeleteRun(runId: string, experimentId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceDeleteRun(runId, experimentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Finds a specific run by ID.
         * @param {string} runId The ID of the run to be retrieved.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceGetRun(runId: string, experimentId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1Run>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceGetRun(runId, experimentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Finds all runs in an experiment given by experiment ID.  If experiment id is not specified, finds all runs across all experiments.
         * @param {string} [namespace] Optional input field. Filters based on the namespace.
         * @param {string} [experimentId] The ID of the parent experiment. If empty, response includes runs across all experiments.
         * @param {string} [pageToken] A page token to request the next page of results. The token is acquired from the nextPageToken field of the response from the previous ListRuns call or can be omitted when fetching the first page.
         * @param {number} [pageSize] The number of runs to be listed per page. If there are more runs than this number, the response message will contain a nextPageToken field you can use to fetch the next page.
         * @param {string} [sortBy] Can be format of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot; (Example, \&quot;name asc\&quot; or \&quot;id desc\&quot;). Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized Filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceListRuns(namespace?: string, experimentId?: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1ListRunsResponse>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceListRuns(namespace, experimentId, pageToken, pageSize, sortBy, filter, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Finds artifact data in a run.
         * @param {string} runId ID of the run.
         * @param {string} nodeId ID of the running node.
         * @param {string} artifactName Name of the artifact.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceReadArtifact(runId: string, nodeId: string, artifactName: string, experimentId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1ReadArtifactResponse>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceReadArtifact(runId, nodeId, artifactName, experimentId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Re-initiates a failed or terminated run.
         * @param {string} runId The ID of the run to be retried.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceRetryRun(runId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceRetryRun(runId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Terminates an active run.
         * @param {string} runId The ID of the run to be terminated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceTerminateRun(runId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceTerminateRun(runId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Restores an archived run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be restored.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceUnarchiveRun(runId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await RunServiceApiAxiosParamCreator(configuration).runServiceUnarchiveRun(runId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * RunServiceApi - factory interface
 * @export
 */
export const RunServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Archives a run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be archived.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceArchiveRun(runId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return RunServiceApiFp(configuration).runServiceArchiveRun(runId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new run in an experiment specified by experiment ID.  If experiment ID is not specified, the run is created in the default experiment.
         * @param {V2beta1Run} body Run to be created.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceCreateRun(body: V2beta1Run, experimentId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1Run>> {
            return RunServiceApiFp(configuration).runServiceCreateRun(body, experimentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be deleted.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceDeleteRun(runId: string, experimentId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return RunServiceApiFp(configuration).runServiceDeleteRun(runId, experimentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finds a specific run by ID.
         * @param {string} runId The ID of the run to be retrieved.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceGetRun(runId: string, experimentId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1Run>> {
            return RunServiceApiFp(configuration).runServiceGetRun(runId, experimentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finds all runs in an experiment given by experiment ID.  If experiment id is not specified, finds all runs across all experiments.
         * @param {string} [namespace] Optional input field. Filters based on the namespace.
         * @param {string} [experimentId] The ID of the parent experiment. If empty, response includes runs across all experiments.
         * @param {string} [pageToken] A page token to request the next page of results. The token is acquired from the nextPageToken field of the response from the previous ListRuns call or can be omitted when fetching the first page.
         * @param {number} [pageSize] The number of runs to be listed per page. If there are more runs than this number, the response message will contain a nextPageToken field you can use to fetch the next page.
         * @param {string} [sortBy] Can be format of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot; (Example, \&quot;name asc\&quot; or \&quot;id desc\&quot;). Ascending by default.
         * @param {string} [filter] A url-encoded, JSON-serialized Filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceListRuns(namespace?: string, experimentId?: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1ListRunsResponse>> {
            return RunServiceApiFp(configuration).runServiceListRuns(namespace, experimentId, pageToken, pageSize, sortBy, filter, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Finds artifact data in a run.
         * @param {string} runId ID of the run.
         * @param {string} nodeId ID of the running node.
         * @param {string} artifactName Name of the artifact.
         * @param {string} [experimentId] The ID of the parent experiment.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceReadArtifact(runId: string, nodeId: string, artifactName: string, experimentId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1ReadArtifactResponse>> {
            return RunServiceApiFp(configuration).runServiceReadArtifact(runId, nodeId, artifactName, experimentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Re-initiates a failed or terminated run.
         * @param {string} runId The ID of the run to be retried.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceRetryRun(runId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return RunServiceApiFp(configuration).runServiceRetryRun(runId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Terminates an active run.
         * @param {string} runId The ID of the run to be terminated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceTerminateRun(runId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return RunServiceApiFp(configuration).runServiceTerminateRun(runId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Restores an archived run in an experiment given by run ID and experiment ID.
         * @param {string} runId The ID of the run to be restored.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runServiceUnarchiveRun(runId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return RunServiceApiFp(configuration).runServiceUnarchiveRun(runId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RunServiceApi - object-oriented interface
 * @export
 * @class RunServiceApi
 * @extends {BaseAPI}
 */
export class RunServiceApi extends BaseAPI {
    /**
     * 
     * @summary Archives a run in an experiment given by run ID and experiment ID.
     * @param {string} runId The ID of the run to be archived.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceArchiveRun(runId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return RunServiceApiFp(this.configuration).runServiceArchiveRun(runId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Creates a new run in an experiment specified by experiment ID.  If experiment ID is not specified, the run is created in the default experiment.
     * @param {V2beta1Run} body Run to be created.
     * @param {string} [experimentId] The ID of the parent experiment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceCreateRun(body: V2beta1Run, experimentId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1Run>> {
        return RunServiceApiFp(this.configuration).runServiceCreateRun(body, experimentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Deletes a run in an experiment given by run ID and experiment ID.
     * @param {string} runId The ID of the run to be deleted.
     * @param {string} [experimentId] The ID of the parent experiment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceDeleteRun(runId: string, experimentId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return RunServiceApiFp(this.configuration).runServiceDeleteRun(runId, experimentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Finds a specific run by ID.
     * @param {string} runId The ID of the run to be retrieved.
     * @param {string} [experimentId] The ID of the parent experiment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceGetRun(runId: string, experimentId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1Run>> {
        return RunServiceApiFp(this.configuration).runServiceGetRun(runId, experimentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Finds all runs in an experiment given by experiment ID.  If experiment id is not specified, finds all runs across all experiments.
     * @param {string} [namespace] Optional input field. Filters based on the namespace.
     * @param {string} [experimentId] The ID of the parent experiment. If empty, response includes runs across all experiments.
     * @param {string} [pageToken] A page token to request the next page of results. The token is acquired from the nextPageToken field of the response from the previous ListRuns call or can be omitted when fetching the first page.
     * @param {number} [pageSize] The number of runs to be listed per page. If there are more runs than this number, the response message will contain a nextPageToken field you can use to fetch the next page.
     * @param {string} [sortBy] Can be format of \&quot;field_name\&quot;, \&quot;field_name asc\&quot; or \&quot;field_name desc\&quot; (Example, \&quot;name asc\&quot; or \&quot;id desc\&quot;). Ascending by default.
     * @param {string} [filter] A url-encoded, JSON-serialized Filter protocol buffer (see [filter.proto](https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto)).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceListRuns(namespace?: string, experimentId?: string, pageToken?: string, pageSize?: number, sortBy?: string, filter?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1ListRunsResponse>> {
        return RunServiceApiFp(this.configuration).runServiceListRuns(namespace, experimentId, pageToken, pageSize, sortBy, filter, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Finds artifact data in a run.
     * @param {string} runId ID of the run.
     * @param {string} nodeId ID of the running node.
     * @param {string} artifactName Name of the artifact.
     * @param {string} [experimentId] The ID of the parent experiment.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceReadArtifact(runId: string, nodeId: string, artifactName: string, experimentId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1ReadArtifactResponse>> {
        return RunServiceApiFp(this.configuration).runServiceReadArtifact(runId, nodeId, artifactName, experimentId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Re-initiates a failed or terminated run.
     * @param {string} runId The ID of the run to be retried.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceRetryRun(runId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return RunServiceApiFp(this.configuration).runServiceRetryRun(runId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Terminates an active run.
     * @param {string} runId The ID of the run to be terminated.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceTerminateRun(runId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return RunServiceApiFp(this.configuration).runServiceTerminateRun(runId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Restores an archived run in an experiment given by run ID and experiment ID.
     * @param {string} runId The ID of the run to be restored.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RunServiceApi
     */
    public async runServiceUnarchiveRun(runId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return RunServiceApiFp(this.configuration).runServiceUnarchiveRun(runId, options).then((request) => request(this.axios, this.basePath));
    }
}
