/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { RuntimeError } from '../models';
import { V2beta1Visualization } from '../models';
/**
 * VisualizationServiceApi - axios parameter creator
 * @export
 */
export const VisualizationServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V2beta1Visualization} body 
         * @param {string} namespace 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        visualizationServiceCreateVisualizationV1: async (body: V2beta1Visualization, namespace: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling visualizationServiceCreateVisualizationV1.');
            }
            // verify required parameter 'namespace' is not null or undefined
            if (namespace === null || namespace === undefined) {
                throw new RequiredError('namespace','Required parameter namespace was null or undefined when calling visualizationServiceCreateVisualizationV1.');
            }
            const localVarPath = `/apis/v2beta1/visualizations/{namespace}`
                .replace(`{${"namespace"}}`, encodeURIComponent(String(namespace)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VisualizationServiceApi - functional programming interface
 * @export
 */
export const VisualizationServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V2beta1Visualization} body 
         * @param {string} namespace 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async visualizationServiceCreateVisualizationV1(body: V2beta1Visualization, namespace: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<V2beta1Visualization>>> {
            const localVarAxiosArgs = await VisualizationServiceApiAxiosParamCreator(configuration).visualizationServiceCreateVisualizationV1(body, namespace, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VisualizationServiceApi - factory interface
 * @export
 */
export const VisualizationServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {V2beta1Visualization} body 
         * @param {string} namespace 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async visualizationServiceCreateVisualizationV1(body: V2beta1Visualization, namespace: string, options?: AxiosRequestConfig): Promise<AxiosResponse<V2beta1Visualization>> {
            return VisualizationServiceApiFp(configuration).visualizationServiceCreateVisualizationV1(body, namespace, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VisualizationServiceApi - object-oriented interface
 * @export
 * @class VisualizationServiceApi
 * @extends {BaseAPI}
 */
export class VisualizationServiceApi extends BaseAPI {
    /**
     * 
     * @param {V2beta1Visualization} body 
     * @param {string} namespace 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VisualizationServiceApi
     */
    public async visualizationServiceCreateVisualizationV1(body: V2beta1Visualization, namespace: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<V2beta1Visualization>> {
        return VisualizationServiceApiFp(this.configuration).visualizationServiceCreateVisualizationV1(body, namespace, options).then((request) => request(this.axios, this.basePath));
    }
}
