/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $v2beta1PipelineVersion = {
    properties: {
        pipeline_id: {
            type: 'string',
            description: `Required input field. Unique ID of the parent pipeline.`,
        },
        pipeline_version_id: {
            type: 'string',
            description: `Output. Unique pipeline version ID. Generated by API server.`,
        },
        display_name: {
            type: 'string',
            description: `Required input field. Pipeline version name provided by user.`,
        },
        description: {
            type: 'string',
            description: `Optional input field. Short description of the pipeline version.`,
        },
        created_at: {
            type: 'string',
            description: `Output. Creation time of the pipeline version.`,
            format: 'date-time',
        },
        package_url: {
            type: 'v2beta1Url',
        },
        code_source_url: {
            type: 'string',
            description: `Input. Optional. The URL to the code source of the pipeline version.
            The code is usually the Python definition of the pipeline and potentially
            related the component definitions. This allows users to trace back to how
            the pipeline YAML was created.`,
        },
        pipeline_spec: {
            description: `Output. The pipeline spec for the pipeline version.`,
            properties: {
            },
        },
        error: {
            type: 'googlerpcStatus',
        },
    },
} as const;
