/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $v2beta1Pipeline = {
    properties: {
        pipeline_id: {
            type: 'string',
            description: `Output. Unique pipeline ID. Generated by API server.`,
        },
        display_name: {
            type: 'string',
            description: `Required input field. Pipeline name provided by user.`,
        },
        description: {
            type: 'string',
            description: `Optional input field. A short description of the pipeline.`,
        },
        created_at: {
            type: 'string',
            description: `Output. Creation time of the pipeline.`,
            format: 'date-time',
        },
        namespace: {
            type: 'string',
            description: `Input. A namespace this pipeline belongs to.
            Causes error if user is not authorized to access the specified namespace.
            If not specified in CreatePipeline, default namespace is used.`,
        },
        error: {
            type: 'googlerpcStatus',
        },
    },
} as const;
