/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $v2beta1Run = {
    properties: {
        experiment_id: {
            type: 'string',
            description: `Input. ID of the parent experiment.
            The default experiment ID will be used if this is not specified.`,
        },
        run_id: {
            type: 'string',
            description: `Output. Unique run ID. Generated by API server.`,
        },
        display_name: {
            type: 'string',
            description: `Required input. Name provided by user,
            or auto generated if run is created by a recurring run.`,
        },
        storage_state: {
            type: 'v2beta1RunStorageState',
        },
        description: {
            type: 'string',
            description: `Optional input. Short description of the run.`,
        },
        pipeline_version_id: {
            type: 'string',
            description: `This field is Deprecated. The pipeline version id is under pipeline_version_reference for v2.`,
        },
        pipeline_spec: {
            description: `Pipeline spec.`,
            properties: {
            },
        },
        pipeline_version_reference: {
            type: 'v2beta1PipelineVersionReference',
        },
        runtime_config: {
            type: 'v2beta1RuntimeConfig',
        },
        service_account: {
            type: 'string',
            description: `Optional input. Specifies which kubernetes service account is used.`,
        },
        created_at: {
            type: 'string',
            description: `Output. Creation time of the run.`,
            format: 'date-time',
        },
        scheduled_at: {
            type: 'string',
            description: `Output. When this run is scheduled to start. This could be different from
            created_at. For example, if a run is from a backfilling job that was supposed
            to run 2 month ago, the created_at will be 2 month behind scheduled_at.`,
            format: 'date-time',
        },
        finished_at: {
            type: 'string',
            description: `Output. Completion of the run.`,
            format: 'date-time',
        },
        state: {
            type: 'v2beta1RuntimeState',
        },
        error: {
            type: 'googlerpcStatus',
        },
        run_details: {
            type: 'v2beta1RunDetails',
        },
        recurring_run_id: {
            type: 'string',
            description: `ID of the recurring run that triggered this run.`,
        },
        state_history: {
            type: 'array',
            contains: {
                type: 'v2beta1RuntimeStatus',
            },
        },
    },
} as const;
