/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $v2beta1Experiment = {
    properties: {
        experiment_id: {
            type: 'string',
            description: `Output. Unique experiment ID. Generated by API server.`,
        },
        display_name: {
            type: 'string',
            description: `Required input field. Unique experiment name provided by user.`,
        },
        description: {
            type: 'string',
            description: `Optional input field. Describes the purpose of the experiment.`,
        },
        created_at: {
            type: 'string',
            description: `Output. The time that the experiment was created.`,
            format: 'date-time',
        },
        namespace: {
            type: 'string',
            description: `Optional input field. Specify the namespace this experiment belongs to.`,
        },
        storage_state: {
            type: 'v2beta1ExperimentStorageState',
        },
        last_run_created_at: {
            type: 'string',
            description: `Output. The creation time of the last run in this experiment.`,
            format: 'date-time',
        },
    },
} as const;
