/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export const $v2beta1RecurringRun = {
    properties: {
        recurring_run_id: {
            type: 'string',
            description: `Output. Unique run ID generated by API server.`,
        },
        display_name: {
            type: 'string',
            description: `Required input field. Recurring run name provided by user. Not unique.`,
        },
        description: {
            type: 'string',
            description: `Optional input field. Describes the purpose of the recurring run.`,
        },
        pipeline_version_id: {
            type: 'string',
            description: `This field is Deprecated. The pipeline version id is under pipeline_version_reference for v2.`,
        },
        pipeline_spec: {
            description: `The pipeline spec.`,
            properties: {
            },
        },
        pipeline_version_reference: {
            type: 'v2beta1PipelineVersionReference',
        },
        runtime_config: {
            type: 'v2beta1RuntimeConfig',
        },
        service_account: {
            type: 'string',
            description: `Optional input field. Specifies which Kubernetes service account this recurring run uses.`,
        },
        max_concurrency: {
            type: 'string',
            description: `Required input field.
            Specifies how many runs can be executed concurrently. Range [1-10].`,
            format: 'int64',
        },
        trigger: {
            type: 'v2beta1Trigger',
        },
        mode: {
            type: 'RecurringRunMode',
        },
        created_at: {
            type: 'string',
            description: `Output. The time this recurring run was created.`,
            format: 'date-time',
        },
        updated_at: {
            type: 'string',
            description: `Output. The last time this recurring run was updated.`,
            format: 'date-time',
        },
        status: {
            type: 'v2beta1RecurringRunStatus',
        },
        error: {
            type: 'googlerpcStatus',
        },
        no_catchup: {
            type: 'boolean',
            description: `Optional input field. Whether the recurring run should catch up if behind schedule.
            If true, the recurring run will only schedule the latest interval if behind schedule.
            If false, the recurring run will catch up on each past interval.`,
        },
        namespace: {
            type: 'string',
            description: `TODO (gkclat): consider removing this field if it can be obtained from the parent experiment.
            Output only. Namespace this recurring run belongs to. Derived from the parent experiment.`,
            isReadOnly: true,
        },
        experiment_id: {
            type: 'string',
            description: `ID of the parent experiment this recurring run belongs to.`,
        },
    },
} as const;
