/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Type of resources in pipelines system.
 * @export
 * @enum {string}
 */
export enum AuthorizeRequestResources {
    UNASSIGNEDRESOURCES = 'UNASSIGNED_RESOURCES',
    VIEWERS = 'VIEWERS'
}

