/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProtobufAny } from './protobuf-any';
 /**
 * The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details.  You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
 *
 * @export
 * @interface GooglerpcStatus
 */
export interface GooglerpcStatus {

    /**
     * The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
     *
     * @type {number}
     * @memberof GooglerpcStatus
     */
    code?: number;

    /**
     * A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
     *
     * @type {string}
     * @memberof GooglerpcStatus
     */
    message?: string;

    /**
     * A list of messages that carry the error details.  There is a common set of message types for APIs to use.
     *
     * @type {Array<ProtobufAny>}
     * @memberof GooglerpcStatus
     */
    details?: Array<ProtobufAny>;
}
