/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * A dependent task that requires this one to succeed. Represented by either task_id or pod_name.
 *
 * @export
 * @interface PipelineTaskDetailChildTask
 */
export interface PipelineTaskDetailChildTask {

    /**
     * System-generated ID of a task.
     *
     * @type {string}
     * @memberof PipelineTaskDetailChildTask
     */
    taskId?: string;

    /**
     * Name of the corresponding pod assigned by the orchestration engine. Also known as node_id.
     *
     * @type {string}
     * @memberof PipelineTaskDetailChildTask
     */
    podName?: string;
}
