/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Required input. User setting to enable or disable the recurring run.  Only used for creation of recurring runs. Later updates use enable/disable API.   - DISABLE: The recurring run won't schedule any run if disabled.
 * @export
 * @enum {string}
 */
export enum RecurringRunMode {
    MODEUNSPECIFIED = 'MODE_UNSPECIFIED',
    ENABLE = 'ENABLE',
    DISABLE = 'DISABLE'
}

