/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProtobufAny } from './protobuf-any';
 /**
 * 
 *
 * @export
 * @interface RuntimeError
 */
export interface RuntimeError {

    /**
     * @type {string}
     * @memberof RuntimeError
     */
    error?: string;

    /**
     * @type {number}
     * @memberof RuntimeError
     */
    code?: number;

    /**
     * @type {string}
     * @memberof RuntimeError
     */
    message?: string;

    /**
     * @type {Array<ProtobufAny>}
     * @memberof RuntimeError
     */
    details?: Array<ProtobufAny>;
}
