/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1Pipeline } from './v2beta1-pipeline';
 /**
 * 
 *
 * @export
 * @interface V2beta1ListPipelinesResponse
 */
export interface V2beta1ListPipelinesResponse {

    /**
     * Returned pipelines.
     *
     * @type {Array<V2beta1Pipeline>}
     * @memberof V2beta1ListPipelinesResponse
     */
    pipelines?: Array<V2beta1Pipeline>;

    /**
     * The total number of pipelines for the given query.
     *
     * @type {number}
     * @memberof V2beta1ListPipelinesResponse
     */
    totalSize?: number;

    /**
     * The token to list the next page of pipelines. This token can be used on the next ListPipelinesRequest.
     *
     * @type {string}
     * @memberof V2beta1ListPipelinesResponse
     */
    nextPageToken?: string;
}
