/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GooglerpcStatus } from './googlerpc-status';
 /**
 * 
 *
 * @export
 * @interface V2beta1Pipeline
 */
export interface V2beta1Pipeline {

    /**
     * Output. Unique pipeline ID. Generated by API server.
     *
     * @type {string}
     * @memberof V2beta1Pipeline
     */
    pipelineId?: string;

    /**
     * Required input field. Pipeline name provided by user.
     *
     * @type {string}
     * @memberof V2beta1Pipeline
     */
    displayName?: string;

    /**
     * Optional input field. A short description of the pipeline.
     *
     * @type {string}
     * @memberof V2beta1Pipeline
     */
    description?: string;

    /**
     * Output. Creation time of the pipeline.
     *
     * @type {Date}
     * @memberof V2beta1Pipeline
     */
    createdAt?: Date;

    /**
     * Input. A namespace this pipeline belongs to. Causes error if user is not authorized to access the specified namespace. If not specified in CreatePipeline, default namespace is used.
     *
     * @type {string}
     * @memberof V2beta1Pipeline
     */
    namespace?: string;

    /**
     * @type {GooglerpcStatus}
     * @memberof V2beta1Pipeline
     */
    error?: GooglerpcStatus;
}
