/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GooglerpcStatus } from './googlerpc-status';
import { V2beta1Url } from './v2beta1-url';
 /**
 * 
 *
 * @export
 * @interface V2beta1PipelineVersion
 */
export interface V2beta1PipelineVersion {

    /**
     * Required input field. Unique ID of the parent pipeline.
     *
     * @type {string}
     * @memberof V2beta1PipelineVersion
     */
    pipelineId?: string;

    /**
     * Output. Unique pipeline version ID. Generated by API server.
     *
     * @type {string}
     * @memberof V2beta1PipelineVersion
     */
    pipelineVersionId?: string;

    /**
     * Required input field. Pipeline version name provided by user.
     *
     * @type {string}
     * @memberof V2beta1PipelineVersion
     */
    displayName?: string;

    /**
     * Optional input field. Short description of the pipeline version.
     *
     * @type {string}
     * @memberof V2beta1PipelineVersion
     */
    description?: string;

    /**
     * Output. Creation time of the pipeline version.
     *
     * @type {Date}
     * @memberof V2beta1PipelineVersion
     */
    createdAt?: Date;

    /**
     * @type {V2beta1Url}
     * @memberof V2beta1PipelineVersion
     */
    packageUrl?: V2beta1Url;

    /**
     * Input. Optional. The URL to the code source of the pipeline version. The code is usually the Python definition of the pipeline and potentially related the component definitions. This allows users to trace back to how the pipeline YAML was created.
     *
     * @type {string}
     * @memberof V2beta1PipelineVersion
     */
    codeSourceUrl?: string;

    /**
     * Output. The pipeline spec for the pipeline version.
     *
     * @type {any}
     * @memberof V2beta1PipelineVersion
     */
    pipelineSpec?: any;

    /**
     * @type {GooglerpcStatus}
     * @memberof V2beta1PipelineVersion
     */
    error?: GooglerpcStatus;
}
