/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * PeriodicSchedule allow scheduling the recurring run periodically with certain interval.
 *
 * @export
 * @interface V2beta1PeriodicSchedule
 */
export interface V2beta1PeriodicSchedule {

    /**
     * The start time of the periodic recurring run.
     *
     * @type {Date}
     * @memberof V2beta1PeriodicSchedule
     */
    startTime?: Date;

    /**
     * The end time of the periodic recurring run.
     *
     * @type {Date}
     * @memberof V2beta1PeriodicSchedule
     */
    endTime?: Date;

    /**
     * The time interval between the starting time of consecutive recurring runs.
     *
     * @type {string}
     * @memberof V2beta1PeriodicSchedule
     */
    intervalSecond?: string;
}
