/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GooglerpcStatus } from './googlerpc-status';
import { V2beta1RuntimeState } from './v2beta1-runtime-state';
 /**
 * Timestamped representation of a runtime state with an optional error.
 *
 * @export
 * @interface V2beta1RuntimeStatus
 */
export interface V2beta1RuntimeStatus {

    /**
     * Update time of this state.
     *
     * @type {Date}
     * @memberof V2beta1RuntimeStatus
     */
    updateTime?: Date;

    /**
     * @type {V2beta1RuntimeState}
     * @memberof V2beta1RuntimeStatus
     */
    state?: V2beta1RuntimeState;

    /**
     * @type {GooglerpcStatus}
     * @memberof V2beta1RuntimeStatus
     */
    error?: GooglerpcStatus;
}
