/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Operation is the operation to apply.   - OPERATION_UNSPECIFIED: Default operation. This operation is not used.  - EQUALS: Operation on scalar values. Only applies to one of |int_value|, |long_value|, |string_value| or |timestamp_value|.  - NOT_EQUALS: Negated EQUALS.  - GREATER_THAN: Greater than operation.  - GREATER_THAN_EQUALS: Greater than or equals operation.  - LESS_THAN: Less than operation.  - LESS_THAN_EQUALS: Less than or equals operation  - IN: Checks if the value is a member of a given array, which should be one of |int_values|, |long_values| or |string_values|.  - IS_SUBSTRING: Checks if the value contains |string_value| as a substring match. Only applies to |string_value|.
 * @export
 * @enum {string}
 */
export enum V2beta1PredicateOperation {
    OPERATIONUNSPECIFIED = 'OPERATION_UNSPECIFIED',
    EQUALS = 'EQUALS',
    NOTEQUALS = 'NOT_EQUALS',
    GREATERTHAN = 'GREATER_THAN',
    GREATERTHANEQUALS = 'GREATER_THAN_EQUALS',
    LESSTHAN = 'LESS_THAN',
    LESSTHANEQUALS = 'LESS_THAN_EQUALS',
    IN = 'IN',
    ISSUBSTRING = 'IS_SUBSTRING'
}

