/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * A list of artifact metadata.
 *
 * @export
 * @interface V2beta1ArtifactList
 */
export interface V2beta1ArtifactList {

    /**
     * A list of artifact metadata ids.
     *
     * @type {Array<string>}
     * @memberof V2beta1ArtifactList
     */
    artifactIds?: Array<string>;
}
