/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Describes the runtime state of an entity.   - RUNTIME_STATE_UNSPECIFIED: Default value. This value is not used.  - PENDING: Service is preparing to execute an entity.  - RUNNING: Entity execution is in progress.  - SUCCEEDED: Entity completed successfully.  - SKIPPED: Entity has been skipped. For example, due to caching.  - FAILED: Entity execution has failed.  - CANCELING: Entity is being canceled. From this state, an entity may only change its state to SUCCEEDED, FAILED or CANCELED.  - CANCELED: Entity has been canceled.  - PAUSED: Entity has been paused. It can be resumed.
 * @export
 * @enum {string}
 */
export enum V2beta1RuntimeState {
    RUNTIMESTATEUNSPECIFIED = 'RUNTIME_STATE_UNSPECIFIED',
    PENDING = 'PENDING',
    RUNNING = 'RUNNING',
    SUCCEEDED = 'SUCCEEDED',
    SKIPPED = 'SKIPPED',
    FAILED = 'FAILED',
    CANCELING = 'CANCELING',
    CANCELED = 'CANCELED',
    PAUSED = 'PAUSED'
}

