/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1Pipeline } from './v2beta1-pipeline';
import { V2beta1PipelineVersion } from './v2beta1-pipeline-version';
 /**
 * 
 *
 * @export
 * @interface V2beta1CreatePipelineAndVersionRequest
 */
export interface V2beta1CreatePipelineAndVersionRequest {

    /**
     * @type {V2beta1Pipeline}
     * @memberof V2beta1CreatePipelineAndVersionRequest
     */
    pipeline?: V2beta1Pipeline;

    /**
     * @type {V2beta1PipelineVersion}
     * @memberof V2beta1CreatePipelineAndVersionRequest
     */
    pipelineVersion?: V2beta1PipelineVersion;
}
