/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GooglerpcStatus } from './googlerpc-status';
import { V2beta1PipelineVersionReference } from './v2beta1-pipeline-version-reference';
import { V2beta1RunDetails } from './v2beta1-run-details';
import { V2beta1RunStorageState } from './v2beta1-run-storage-state';
import { V2beta1RuntimeConfig } from './v2beta1-runtime-config';
import { V2beta1RuntimeState } from './v2beta1-runtime-state';
import { V2beta1RuntimeStatus } from './v2beta1-runtime-status';
 /**
 * 
 *
 * @export
 * @interface V2beta1Run
 */
export interface V2beta1Run {

    /**
     * Input. ID of the parent experiment. The default experiment ID will be used if this is not specified.
     *
     * @type {string}
     * @memberof V2beta1Run
     */
    experimentId?: string;

    /**
     * Output. Unique run ID. Generated by API server.
     *
     * @type {string}
     * @memberof V2beta1Run
     */
    runId?: string;

    /**
     * Required input. Name provided by user, or auto generated if run is created by a recurring run.
     *
     * @type {string}
     * @memberof V2beta1Run
     */
    displayName?: string;

    /**
     * @type {V2beta1RunStorageState}
     * @memberof V2beta1Run
     */
    storageState?: V2beta1RunStorageState;

    /**
     * Optional input. Short description of the run.
     *
     * @type {string}
     * @memberof V2beta1Run
     */
    description?: string;

    /**
     * This field is Deprecated. The pipeline version id is under pipeline_version_reference for v2.
     *
     * @type {string}
     * @memberof V2beta1Run
     */
    pipelineVersionId?: string;

    /**
     * Pipeline spec.
     *
     * @type {any}
     * @memberof V2beta1Run
     */
    pipelineSpec?: any;

    /**
     * @type {V2beta1PipelineVersionReference}
     * @memberof V2beta1Run
     */
    pipelineVersionReference?: V2beta1PipelineVersionReference;

    /**
     * @type {V2beta1RuntimeConfig}
     * @memberof V2beta1Run
     */
    runtimeConfig?: V2beta1RuntimeConfig;

    /**
     * Optional input. Specifies which kubernetes service account is used.
     *
     * @type {string}
     * @memberof V2beta1Run
     */
    serviceAccount?: string;

    /**
     * Output. Creation time of the run.
     *
     * @type {Date}
     * @memberof V2beta1Run
     */
    createdAt?: Date;

    /**
     * Output. When this run is scheduled to start. This could be different from created_at. For example, if a run is from a backfilling job that was supposed to run 2 month ago, the created_at will be 2 month behind scheduled_at.
     *
     * @type {Date}
     * @memberof V2beta1Run
     */
    scheduledAt?: Date;

    /**
     * Output. Completion of the run.
     *
     * @type {Date}
     * @memberof V2beta1Run
     */
    finishedAt?: Date;

    /**
     * @type {V2beta1RuntimeState}
     * @memberof V2beta1Run
     */
    state?: V2beta1RuntimeState;

    /**
     * @type {GooglerpcStatus}
     * @memberof V2beta1Run
     */
    error?: GooglerpcStatus;

    /**
     * @type {V2beta1RunDetails}
     * @memberof V2beta1Run
     */
    runDetails?: V2beta1RunDetails;

    /**
     * ID of the recurring run that triggered this run.
     *
     * @type {string}
     * @memberof V2beta1Run
     */
    recurringRunId?: string;

    /**
     * Output. A sequence of run statuses. This field keeps a record  of state transitions.
     *
     * @type {Array<V2beta1RuntimeStatus>}
     * @memberof V2beta1Run
     */
    stateHistory?: Array<V2beta1RuntimeStatus>;
}
