/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1Run } from './v2beta1-run';
 /**
 * 
 *
 * @export
 * @interface V2beta1ListRunsResponse
 */
export interface V2beta1ListRunsResponse {

    /**
     * List of retrieved runs.
     *
     * @type {Array<V2beta1Run>}
     * @memberof V2beta1ListRunsResponse
     */
    runs?: Array<V2beta1Run>;

    /**
     * The total number of runs for the given query.
     *
     * @type {number}
     * @memberof V2beta1ListRunsResponse
     */
    totalSize?: number;

    /**
     * The token to list the next page of runs.
     *
     * @type {string}
     * @memberof V2beta1ListRunsResponse
     */
    nextPageToken?: string;
}
