/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1PipelineTaskDetail } from './v2beta1-pipeline-task-detail';
 /**
 * Runtime details of a run.
 *
 * @export
 * @interface V2beta1RunDetails
 */
export interface V2beta1RunDetails {

    /**
     * Pipeline context ID of a run.
     *
     * @type {string}
     * @memberof V2beta1RunDetails
     */
    pipelineContextId?: string;

    /**
     * Pipeline run context ID of a run.
     *
     * @type {string}
     * @memberof V2beta1RunDetails
     */
    pipelineRunContextId?: string;

    /**
     * Runtime details of the tasks that belong to the run.
     *
     * @type {Array<V2beta1PipelineTaskDetail>}
     * @memberof V2beta1RunDetails
     */
    taskDetails?: Array<V2beta1PipelineTaskDetail>;
}
