/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * The runtime config.
 *
 * @export
 * @interface V2beta1RuntimeConfig
 */
export interface V2beta1RuntimeConfig {

    /**
     * The runtime parameters of the Pipeline. The parameters will be used to replace the placeholders at runtime.
     *
     * @type {{ [key: string]: any; }}
     * @memberof V2beta1RuntimeConfig
     */
    parameters?: { [key: string]: any; };

    /**
     * @type {string}
     * @memberof V2beta1RuntimeConfig
     */
    pipelineRoot?: string;
}
