/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GooglerpcStatus } from './googlerpc-status';
import { RecurringRunMode } from './recurring-run-mode';
import { V2beta1PipelineVersionReference } from './v2beta1-pipeline-version-reference';
import { V2beta1RecurringRunStatus } from './v2beta1-recurring-run-status';
import { V2beta1RuntimeConfig } from './v2beta1-runtime-config';
import { V2beta1Trigger } from './v2beta1-trigger';
 /**
 * 
 *
 * @export
 * @interface V2beta1RecurringRun
 */
export interface V2beta1RecurringRun {

    /**
     * Output. Unique run ID generated by API server.
     *
     * @type {string}
     * @memberof V2beta1RecurringRun
     */
    recurringRunId?: string;

    /**
     * Required input field. Recurring run name provided by user. Not unique.
     *
     * @type {string}
     * @memberof V2beta1RecurringRun
     */
    displayName?: string;

    /**
     * Optional input field. Describes the purpose of the recurring run.
     *
     * @type {string}
     * @memberof V2beta1RecurringRun
     */
    description?: string;

    /**
     * This field is Deprecated. The pipeline version id is under pipeline_version_reference for v2.
     *
     * @type {string}
     * @memberof V2beta1RecurringRun
     */
    pipelineVersionId?: string;

    /**
     * The pipeline spec.
     *
     * @type {any}
     * @memberof V2beta1RecurringRun
     */
    pipelineSpec?: any;

    /**
     * @type {V2beta1PipelineVersionReference}
     * @memberof V2beta1RecurringRun
     */
    pipelineVersionReference?: V2beta1PipelineVersionReference;

    /**
     * @type {V2beta1RuntimeConfig}
     * @memberof V2beta1RecurringRun
     */
    runtimeConfig?: V2beta1RuntimeConfig;

    /**
     * Optional input field. Specifies which Kubernetes service account this recurring run uses.
     *
     * @type {string}
     * @memberof V2beta1RecurringRun
     */
    serviceAccount?: string;

    /**
     * Required input field. Specifies how many runs can be executed concurrently. Range [1-10].
     *
     * @type {string}
     * @memberof V2beta1RecurringRun
     */
    maxConcurrency?: string;

    /**
     * @type {V2beta1Trigger}
     * @memberof V2beta1RecurringRun
     */
    trigger?: V2beta1Trigger;

    /**
     * @type {RecurringRunMode}
     * @memberof V2beta1RecurringRun
     */
    mode?: RecurringRunMode;

    /**
     * Output. The time this recurring run was created.
     *
     * @type {Date}
     * @memberof V2beta1RecurringRun
     */
    createdAt?: Date;

    /**
     * Output. The last time this recurring run was updated.
     *
     * @type {Date}
     * @memberof V2beta1RecurringRun
     */
    updatedAt?: Date;

    /**
     * @type {V2beta1RecurringRunStatus}
     * @memberof V2beta1RecurringRun
     */
    status?: V2beta1RecurringRunStatus;

    /**
     * @type {GooglerpcStatus}
     * @memberof V2beta1RecurringRun
     */
    error?: GooglerpcStatus;

    /**
     * Optional input field. Whether the recurring run should catch up if behind schedule. If true, the recurring run will only schedule the latest interval if behind schedule. If false, the recurring run will catch up on each past interval.
     *
     * @type {boolean}
     * @memberof V2beta1RecurringRun
     */
    noCatchup?: boolean;

    /**
     * TODO (gkclat): consider removing this field if it can be obtained from the parent experiment. Output only. Namespace this recurring run belongs to. Derived from the parent experiment.
     *
     * @type {string}
     * @memberof V2beta1RecurringRun
     */
    namespace?: string;

    /**
     * ID of the parent experiment this recurring run belongs to.
     *
     * @type {string}
     * @memberof V2beta1RecurringRun
     */
    experimentId?: string;
}
