/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1RecurringRun } from './v2beta1-recurring-run';
 /**
 * 
 *
 * @export
 * @interface V2beta1ListRecurringRunsResponse
 */
export interface V2beta1ListRecurringRunsResponse {

    /**
     * A list of recurring runs returned.
     *
     * @type {Array<V2beta1RecurringRun>}
     * @memberof V2beta1ListRecurringRunsResponse
     */
    recurringRuns?: Array<V2beta1RecurringRun>;

    /**
     * The total number of recurring runs for the given query.
     *
     * @type {number}
     * @memberof V2beta1ListRecurringRunsResponse
     */
    totalSize?: number;

    /**
     * The token to list the next page of recurring runs.
     *
     * @type {string}
     * @memberof V2beta1ListRecurringRunsResponse
     */
    nextPageToken?: string;
}
