/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Runtime information of a pipeline task executor.
 *
 * @export
 * @interface V2beta1PipelineTaskExecutorDetail
 */
export interface V2beta1PipelineTaskExecutorDetail {

    /**
     * The name of the job for the main container execution.
     *
     * @type {string}
     * @memberof V2beta1PipelineTaskExecutorDetail
     */
    mainJob?: string;

    /**
     * The name of the job for the pre-caching-check container execution. This job will be available if the Run.pipeline_spec specifies the `pre_caching_check` hook in the lifecycle events.
     *
     * @type {string}
     * @memberof V2beta1PipelineTaskExecutorDetail
     */
    preCachingCheckJob?: string;

    /**
     * The names of the previously failed job for the main container executions. The list includes the all attempts in chronological order.
     *
     * @type {Array<string>}
     * @memberof V2beta1PipelineTaskExecutorDetail
     */
    failedMainJobs?: Array<string>;

    /**
     * The names of the previously failed job for the pre-caching-check container executions. This job will be available if the Run.pipeline_spec specifies the `pre_caching_check` hook in the lifecycle events. The list includes the all attempts in chronological order.
     *
     * @type {Array<string>}
     * @memberof V2beta1PipelineTaskExecutorDetail
     */
    failedPreCachingCheckJobs?: Array<string>;
}
