/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PredicateIntValues } from './predicate-int-values';
import { PredicateLongValues } from './predicate-long-values';
import { PredicateStringValues } from './predicate-string-values';
import { V2beta1PredicateOperation } from './v2beta1-predicate-operation';
 /**
 * Predicate captures individual conditions that must be true for a resource being filtered.
 *
 * @export
 * @interface V2beta1Predicate
 */
export interface V2beta1Predicate {

    /**
     * @type {V2beta1PredicateOperation}
     * @memberof V2beta1Predicate
     */
    operation?: V2beta1PredicateOperation;

    /**
     * Key for the operation (first argument).
     *
     * @type {string}
     * @memberof V2beta1Predicate
     */
    key?: string;

    /**
     * Integer.
     *
     * @type {number}
     * @memberof V2beta1Predicate
     */
    intValue?: number;

    /**
     * Long integer.
     *
     * @type {string}
     * @memberof V2beta1Predicate
     */
    longValue?: string;

    /**
     * String.
     *
     * @type {string}
     * @memberof V2beta1Predicate
     */
    stringValue?: string;

    /**
     * Timestamp values will be converted to Unix time (seconds since the epoch) prior to being used in a filtering operation.
     *
     * @type {Date}
     * @memberof V2beta1Predicate
     */
    timestampValue?: Date;

    /**
     * @type {PredicateIntValues}
     * @memberof V2beta1Predicate
     */
    intValues?: PredicateIntValues;

    /**
     * @type {PredicateLongValues}
     * @memberof V2beta1Predicate
     */
    longValues?: PredicateLongValues;

    /**
     * @type {PredicateStringValues}
     * @memberof V2beta1Predicate
     */
    stringValues?: PredicateStringValues;
}
