/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1PipelineVersion } from './v2beta1-pipeline-version';
 /**
 * 
 *
 * @export
 * @interface V2beta1ListPipelineVersionsResponse
 */
export interface V2beta1ListPipelineVersionsResponse {

    /**
     * Returned pipeline versions.
     *
     * @type {Array<V2beta1PipelineVersion>}
     * @memberof V2beta1ListPipelineVersionsResponse
     */
    pipelineVersions?: Array<V2beta1PipelineVersion>;

    /**
     * The token to list the next page of pipeline versions.
     *
     * @type {string}
     * @memberof V2beta1ListPipelineVersionsResponse
     */
    nextPageToken?: string;

    /**
     * The total number of pipeline versions for the given query.
     *
     * @type {number}
     * @memberof V2beta1ListPipelineVersionsResponse
     */
    totalSize?: number;
}
