/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1CronSchedule } from './v2beta1-cron-schedule';
import { V2beta1PeriodicSchedule } from './v2beta1-periodic-schedule';
 /**
 * Trigger defines what starts a pipeline run.
 *
 * @export
 * @interface V2beta1Trigger
 */
export interface V2beta1Trigger {

    /**
     * @type {V2beta1CronSchedule}
     * @memberof V2beta1Trigger
     */
    cronSchedule?: V2beta1CronSchedule;

    /**
     * @type {V2beta1PeriodicSchedule}
     * @memberof V2beta1Trigger
     */
    periodicSchedule?: V2beta1PeriodicSchedule;
}
