/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * CronSchedule allow scheduling the recurring run with unix-like cron.
 *
 * @export
 * @interface V2beta1CronSchedule
 */
export interface V2beta1CronSchedule {

    /**
     * The start time of the cron job.
     *
     * @type {Date}
     * @memberof V2beta1CronSchedule
     */
    startTime?: Date;

    /**
     * The end time of the cron job.
     *
     * @type {Date}
     * @memberof V2beta1CronSchedule
     */
    endTime?: Date;

    /**
     * @type {string}
     * @memberof V2beta1CronSchedule
     */
    cron?: string;
}
