/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GooglerpcStatus } from './googlerpc-status';
import { PipelineTaskDetailChildTask } from './pipeline-task-detail-child-task';
import { V2beta1ArtifactList } from './v2beta1-artifact-list';
import { V2beta1PipelineTaskExecutorDetail } from './v2beta1-pipeline-task-executor-detail';
import { V2beta1RuntimeState } from './v2beta1-runtime-state';
import { V2beta1RuntimeStatus } from './v2beta1-runtime-status';
 /**
 * Runtime information of a task execution.
 *
 * @export
 * @interface V2beta1PipelineTaskDetail
 */
export interface V2beta1PipelineTaskDetail {

    /**
     * ID of the parent run.
     *
     * @type {string}
     * @memberof V2beta1PipelineTaskDetail
     */
    runId?: string;

    /**
     * System-generated ID of a task.
     *
     * @type {string}
     * @memberof V2beta1PipelineTaskDetail
     */
    taskId?: string;

    /**
     * User specified name of a task that is defined in [Pipeline.spec][].
     *
     * @type {string}
     * @memberof V2beta1PipelineTaskDetail
     */
    displayName?: string;

    /**
     * Creation time of a task.
     *
     * @type {Date}
     * @memberof V2beta1PipelineTaskDetail
     */
    createTime?: Date;

    /**
     * Starting time of a task.
     *
     * @type {Date}
     * @memberof V2beta1PipelineTaskDetail
     */
    startTime?: Date;

    /**
     * Completion time of a task.
     *
     * @type {Date}
     * @memberof V2beta1PipelineTaskDetail
     */
    endTime?: Date;

    /**
     * @type {V2beta1PipelineTaskExecutorDetail}
     * @memberof V2beta1PipelineTaskDetail
     */
    executorDetail?: V2beta1PipelineTaskExecutorDetail;

    /**
     * @type {V2beta1RuntimeState}
     * @memberof V2beta1PipelineTaskDetail
     */
    state?: V2beta1RuntimeState;

    /**
     * Execution id of the corresponding entry in ML metadata store.
     *
     * @type {string}
     * @memberof V2beta1PipelineTaskDetail
     */
    executionId?: string;

    /**
     * @type {GooglerpcStatus}
     * @memberof V2beta1PipelineTaskDetail
     */
    error?: GooglerpcStatus;

    /**
     * Input artifacts of the task.
     *
     * @type {{ [key: string]: V2beta1ArtifactList; }}
     * @memberof V2beta1PipelineTaskDetail
     */
    inputs?: { [key: string]: V2beta1ArtifactList; };

    /**
     * Output artifacts of the task.
     *
     * @type {{ [key: string]: V2beta1ArtifactList; }}
     * @memberof V2beta1PipelineTaskDetail
     */
    outputs?: { [key: string]: V2beta1ArtifactList; };

    /**
     * ID of the parent task if the task is within a component scope. Empty if the task is at the root level.
     *
     * @type {string}
     * @memberof V2beta1PipelineTaskDetail
     */
    parentTaskId?: string;

    /**
     * A sequence of task statuses. This field keeps a record  of state transitions.
     *
     * @type {Array<V2beta1RuntimeStatus>}
     * @memberof V2beta1PipelineTaskDetail
     */
    stateHistory?: Array<V2beta1RuntimeStatus>;

    /**
     * Name of the corresponding pod assigned by the orchestration engine. Also known as node_id.
     *
     * @type {string}
     * @memberof V2beta1PipelineTaskDetail
     */
    podName?: string;

    /**
     * Sequence of dependen tasks.
     *
     * @type {Array<PipelineTaskDetailChildTask>}
     * @memberof V2beta1PipelineTaskDetail
     */
    childTasks?: Array<PipelineTaskDetailChildTask>;
}
