/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * Reference to an existing pipeline version.
 *
 * @export
 * @interface V2beta1PipelineVersionReference
 */
export interface V2beta1PipelineVersionReference {

    /**
     * Input. Required. Unique ID of the parent pipeline.
     *
     * @type {string}
     * @memberof V2beta1PipelineVersionReference
     */
    pipelineId?: string;

    /**
     * Input. Optional. Unique ID of an existing pipeline version. If unset, the latest pipeline version is used.
     *
     * @type {string}
     * @memberof V2beta1PipelineVersionReference
     */
    pipelineVersionId?: string;
}
