/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1VisualizationType } from './v2beta1-visualization-type';
 /**
 * 
 *
 * @export
 * @interface V2beta1Visualization
 */
export interface V2beta1Visualization {

    /**
     * @type {V2beta1VisualizationType}
     * @memberof V2beta1Visualization
     */
    type?: V2beta1VisualizationType;

    /**
     * Path pattern of input data to be used during generation of visualizations. This is required when creating the pipeline through CreateVisualization API.
     *
     * @type {string}
     * @memberof V2beta1Visualization
     */
    source?: string;

    /**
     * Variables to be used during generation of a visualization. This should be provided as a JSON string. This is required when creating the pipeline through CreateVisualization API.
     *
     * @type {string}
     * @memberof V2beta1Visualization
     */
    arguments?: string;

    /**
     * Output. Generated visualization html.
     *
     * @type {string}
     * @memberof V2beta1Visualization
     */
    html?: string;

    /**
     * In case any error happens when generating visualizations, only visualization ID and the error message are returned. Client has the flexibility of choosing how to handle the error.
     *
     * @type {string}
     * @memberof V2beta1Visualization
     */
    error?: string;
}
