/* tslint:disable */
/* eslint-disable */
/**
 * Kubeflow Pipelines API
 * This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.
 *
 * OpenAPI spec version: 2.4.1
 * Contact: kubeflow-pipelines@google.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { V2beta1Predicate } from './v2beta1-predicate';
 /**
 * Filter is used to filter resources returned from a ListXXX request.  Example filters: 1) Filter runs with status = 'Running' filter {   predicate {     key: \"status\"     operation: EQUALS     string_value: \"Running\"   } }  2) Filter runs that succeeded since Dec 1, 2018 filter {   predicate {     key: \"status\"     operation: EQUALS     string_value: \"Succeeded\"   }   predicate {     key: \"created_at\"     operation: GREATER_THAN     timestamp_value {       seconds: 1543651200     }   } }  3) Filter runs with one of labels 'label_1' or 'label_2'  filter {   predicate {     key: \"label\"     operation: IN     string_values {       value: 'label_1'       value: 'label_2'     }   } }
 *
 * @export
 * @interface V2beta1Filter
 */
export interface V2beta1Filter {

    /**
     * All predicates are AND-ed when this filter is applied.
     *
     * @type {Array<V2beta1Predicate>}
     * @memberof V2beta1Filter
     */
    predicates?: Array<V2beta1Predicate>;
}
